export const LeaguesEnum: Record<string, string> = {
  MLB: 'MLB',
  MLS: 'MLS',
  NBA: 'NBA',
  NCAAB: 'NCAAB',
  NCAAF: 'NCAAF',
  NCAAMH: 'NCAAMH',
  NCAAWH: 'NCAAWH',
  NCCABB: 'NCCABB',
  NFL: 'NFL',
  NHL: 'NHL',
  NWSL: 'NWSL',
  'OLYMPICS-MEN': 'OLYMPICS-MEN',
  'OLYMPICS-WOMEN': 'OLYMPICS-WOMEN',
  PWHL: 'PWHL',
  WNBA: 'WNBA',
  WNCAAB: 'WNCAAB',
};

export const leagueMapping = {
  MLB: 'mlb/standings',
  MLS: 'soccer/table/_/league/usa.1/standings',
  NBA: 'nba/standings',
  NCAAB: 'mens-college-basketball/standings',
  NCAAF: 'college-football/standings',
  NCAAMH: 'college-sports/rankings',
  NCAAWH: 'college-sports/rankings',
  NCCABB: 'college-sports/rankings',
  NFL: 'nfl/standings',
  NHL: 'nhl/standings',
  NWSL: 'soccer/league/_/name/usa.nwsl/standings',
  WNBA: 'wnba/standings',
  WNCAAB: 'womens-college-basketball/standings',
};
