export const TeamsEnum: Record<string, string> = {
  'NFL-SF': "49ers",
  'NCAAF-ACU': "Abilene Christian Wildcats",
  'NCCABB-ACU': "Abilene Chrstn",
  'NCCABB-AFA': "Air Force",
  'NCCABB-AKR': "Akron",
  'NCAAF-AKR': "Akron Zips",
  'NCCABB-ALA': "Alabama",
  'NCCABB-AAMU': "Alabama A&m",
  'NCAAB-ALA': "Alabama Crimson Tide",
  'NCAAF-ALA': "Alabama Crimson Tide",
  'WNCAAB-ALA': "Alabama Crimson Tide",
  'NCCABB-ALST': "Alabama St",
  'NCCABB-ALCN': "Alcorn St",
  'NCCABB-ALMA': "Alma",
  'NCAAB-AMER': "American",
  'WNCAAB-AMER': "American",
  'NCCABB-AMER': "American",
  'NCAAF-AMH': "Amherst",
  'NHL-ANA': "Anaheim",
  'NCCABB-ANDC': "Anderson Ind",
  'NCAAF-ANN': "Anna Maria",
  'NCCABB-APP': "App State",
  'NCAAF-APP': "App State Mountaineers",
  'NCCABB-UAPB': "Ar-pine Bluff",
  'MLB-ARI': "Arizona",
  'WNCAAB-ARIZ': "Arizona",
  'NCAAB-ARIZ': "Arizona",
  'NCAAF-ARIZ': "Arizona",
  'NCCABB-ARIZ': "Arizona",
  'NCAAB-ASU': "Arizona St",
  'WNCAAB-ASU': "Arizona St",
  'NCAAF-ASU': "Arizona St",
  'NCCABB-ASU': "Arizona St",
  'WNCAAB-ARK': "Arkansas",
  'NCAAB-ARK': "Arkansas",
  'NCAAF-ARK': "Arkansas",
  'NCCABB-ARK': "Arkansas",
  'NCCABB-ARST': "Arkansas St",
  'NCAAF-ARST': "Arkansas State Red Wolves",
  'NCAAF-UAPB': "Arkansas-pine Bluff Golden Lions",
  'NCCABB-ARMY': "Army",
  'MLB-ATH': "Athletics",
  'MLB-ATL': "Atlanta",
  'WNBA-ATL': "Atlanta",
  'NBA-ATL': "Atlanta",
  'MLS-ATL': "Atlanta United Fc",
  'NCAAB-AUB': "Auburn",
  'NCAAF-AUB': "Auburn",
  'WNCAAB-AUB': "Auburn",
  'NCCABB-AUB': "Auburn",
  'NCCABB-AUG': "Augustana Coll",
  'NCCABB-AUR': "Aurora",
  'MLS-ATX': "Austin Fc",
  'NCCABB-APSU': "Austin Peay",
  'NCAAF-APSU': "Austin Peay Governors",
  'NCCABB-BACN': "Baconecg",
  'NCCABB-BAC': "Baconecg",
  'NCCABB-BAKE': "Baker University",
  'NCCABB-CSUB': "Bakersfield",
  'NCCABB-BALL': "Ball State",
  'NCAAF-BALL': "Ball State Cardinals",
  'MLB-BAL': "Baltimore",
  'NCCABB-BAR': "Barry",
  'NCCABB-BARR': "Barry",
  'NCCABB-BAY': "Baylor",
  'NCAAB-BAY': "Baylor Bears",
  'WNCAAB-BAY': "Baylor Bears",
  'NCAAF-BAY': "Baylor Bears",
  'NFL-CHI': "Bears",
  'NCAAB-BELL': "Bellarmine",
  'WNCAAB-BELL': "Bellarmine",
  'NCCABB-BELL': "Bellarmine",
  'NCCABB-BEL': "Belmont",
  'NFL-CIN': "Bengals",
  'NCCABB-BET': "Bethanyks",
  'NCCABB-BETH': "Bethanyks",
  'NCCABB-BCU': "Bethune",
  'NCAAF-BCU': "Bethune-cookman Wildcats",
  'NFL-BUF': "Bills",
  'NCCABB-BING': "Binghamton",
  'NCCABB-BSC': "Birmingham-so.",
  'NCAAF-BOIS': "Boise St",
  'WNCAAB-BOIS': "Boise St",
  'NCAAB-BOIS': "Boise St",
  'NCCABB-BOIS': "Boise St",
  'NHL-BOS': "Boston",
  'NBA-BOS': "Boston",
  'MLB-BOS': "Boston",
  'NCCABB-BC': "Boston College",
  'NCAAB-BC': "Boston College Eagles",
  'NCAAF-BC': "Boston College Eagles",
  'WNCAAB-BC': "Boston College Eagles",
  'PWHL-BOS': "Boston Fleet",
  'NCCABB-BU': "Boston U",
  'NCCABB-BGSU': "Bowling Green",
  'NCAAF-BGSU': "Bowling Green Falcons",
  'NCCABB-BRAD': "Bradley",
  'WNCAAB-BRAD': "Bradley",
  'NCAAB-BRAD': "Bradley",
  'NCAAF-BRST': "Bridgewater St",
  'NFL-DEN': "Broncos",
  'NBA-BKN': "Brooklyn",
  'NCCABB-BRWN': "Brown",
  'WNCAAB-BRWN': "Brown Bears",
  'NFL-CLE': "Browns",
  'NCCABB-BRY': "Bryant",
  'NFL-TB': "Buccaneers",
  'NCCABB-BUCK': "Bucknell",
  'NCAAF-BUENA': "Buena Vista",
  'NCCABB-BUF': "Buffalo",
  'NHL-BUF': "Buffalo",
  'NCAAF-BUFF': "Buffalo Bulls",
  'NCAAB-BUF': "Buffalo Bulls",
  'NCCABB-BUT': "Butler",
  'NCAAB-BUT': "Butler Bulldogs",
  'NCCABB-BYU': "Byu",
  'NCAAF-BYU': "Byu Cougars",
  'WNCAAB-BYU': "Byu Cougars",
  'NCAAB-BYU': "Byu Cougars",
  'NCCABB-CARK': "C Arkansas",
  'NCCABB-CCSU': "C Connecticut",
  'NCCABB-CMU': "C Michigan",
  'NCCABB-CBU': "Ca Baptist",
  'NCAAB-CP': "Cal Poly",
  'WNCAAB-CP': "Cal Poly",
  'NCCABB-CP': "Cal Poly",
  'NCAAF-CP': "Cal Poly",
  'NHL-CGY': "Calgary",
  'NCAAB-CAL': "California",
  'NCCABB-CAL': "California",
  'NCAAF-CAL': "California",
  'WNCAAB-CAL': "California",
  'NCCABB-CPP': "Calpolypom",
  'NCCABB-CPPM': "Calpolypom",
  'NCCABB-CAM': "Campbell",
  'NCAAF-CAM': "Campbell Fighting Camels",
  'OLYMPICS-HOCKEY-WOMEN-CAN': "Canada",
  'OLYMPICS-HOCKEY-MEN-CAN': "Canada",
  'NCCABB-CAN': "Canisius",
  'NFL-ARI': "Cardinals",
  'NHL-CAR': "Carolina",
  'NCAAF-CAR': "Carroll Wi",
  'NCCABB-CENT': "Centenary",
  'NCCABB-CAO': "Centmissou",
  'NCCABB-CMST': "Centmissou",
  'NFL-LAC': "Chargers",
  'NCCABB-COFC': "Charleston",
  'NCCABB-CofC': "Charleston",
  'NCCABB-CHSO': "Charleston So",
  'NCCABB-CLT': "Charlotte",
  'NBA-CHA': "Charlotte",
  'NCAAF-CLT': "Charlotte 49ers",
  'MLS-CLT': "Charlotte Fc",
  'NCCABB-UTC': "Chattanooga",
  'NHL-CHI': "Chicago",
  'NBA-CHI': "Chicago",
  'MLB-CHC': "Chicago",
  'WNBA-CHI': "Chicago",
  'MLB-CHW': "Chicago",
  'NCCABB-CHST': "Chicago St",
  'NFL-KC': "Chiefs",
  'NCCABB-CIN': "Cincinnati",
  'MLB-CIN': "Cincinnati",
  'WNCAAB-CIN': "Cincinnati Bearcats",
  'NCAAB-CIN': "Cincinnati Bearcats",
  'NCAAF-CIN': "Cincinnati Bearcats",
  'NCAAF-CLA': "Claremont-m-s",
  'NCCABB-COP': "Clcc",
  'NCCABB-CLEM': "Clemson",
  'WNCAAB-CLEM': "Clemson Tigers",
  'NCAAB-CLEM': "Clemson Tigers",
  'NCAAF-CLEM': "Clemson Tigers",
  'NBA-CLE': "Cleveland",
  'MLB-CLE': "Cleveland",
  'NCCABB-CLE': "Cleveland St",
  'NCCABB-CON': "Cncrdia Mn",
  'NCCABB-CCU': "Coastal",
  'NCAAF-CCU': "Coastal Carolina Chanticleers",
  'NCCABB-COE': "Coe College",
  'NCAAF-COLBY': "Colby",
  'NCCABB-COLG': "Colgate",
  'NCAAF-MESA': "Colo Mesa",
  'NHL-COL': "Colorado",
  'WNCAAB-COLO': "Colorado",
  'NCAAF-COLO': "Colorado",
  'NCAAB-COLO': "Colorado",
  'NCCABB-COLO': "Colorado",
  'MLB-COL': "Colorado",
  'NCAAB-CSU': "Colorado St",
  'NCCABB-CSU': "Colorado St",
  'NCAAF-CSU': "Colorado St",
  'WNCAAB-CSU': "Colorado St",
  'NFL-IND': "Colts",
  'NCCABB-COLU': "Columbia",
  'WNCAAB-COLU': "Columbia Lions",
  'NHL-CBJ': "Columbus",
  'NFL-WSH': "Commanders",
  'WNBA-CON': "Connecticut",
  'NCCABB-COPP': "Coppin St",
  'WNCAAB-COPP': "Coppin State Eagles",
  'NCCABB-COR': "Cornell",
  'WNCAAB-COR': "Cornell Big Red",
  'NCCABB-CRIA': "Cornell Ia",
  'NFL-DAL': "Cowboys",
  'NCCABB-CREI': "Creighton",
  'WNCAAB-CREI': "Creighton Bluejays",
  'NCAAB-CREI': "Creighton Bluejays",
  'MLS-CLB': "Crew",
  'NCCABB-CSUN': "Csu Northridge",
  'NCAAF-CUR': "Curry",
  'OLYMPICS-HOCKEY-WOMEN-CZE': "Czechia",
  'OLYMPICS-HOCKEY-MEN-CZE': "Czechia",
  'NBA-DAL': "Dallas",
  'NHL-DAL': "Dallas",
  'WNBA-DAL': "Dallas",
  'NCCABB-DBU': "Dallas Baptist",
  'NCCABB-DART': "Dartmouth",
  'WNCAAB-DART': "Dartmouth Big Green",
  'NCCABB-DAV': "Davidson",
  'NCAAB-DAV': "Davidson Wildcats",
  'NCCABB-DAY': "Dayton",
  'NCAAB-DAY': "Dayton Flyers",
  'WNCAAB-DEL': "Delaware",
  'NCAAF-DEL': "Delaware",
  'NCCABB-DEL': "Delaware",
  'NCAAB-DEL': "Delaware",
  'NCCABB-DSU': "Delaware St",
  'OLYMPICS-HOCKEY-MEN-DEN': "Denmark",
  'NBA-DEN': "Denver",
  'NCCABB-DEN': "Denver",
  'NCAAB-DEP': "Depaul Blue Demons",
  'WNCAAB-DEP': "Depaul Blue Demons",
  'NCCABB-DEP': "Depauw Univers",
  'NBA-DET': "Detroit",
  'NHL-DET': "Detroit",
  'MLB-DET': "Detroit",
  'NCCABB-DETM': "Detroit Mercy",
  'NFL-MIA': "Dolphins",
  'NCCABB-DRKE': "Drake",
  'NCCABB-DREX': "Drexel",
  'NCAAF-DUB': "Dubuque",
  'NCCABB-DUKE': "Duke",
  'NCAAB-DUKE': "Duke Blue Devils",
  'WNCAAB-DUKE': "Duke Blue Devils",
  'NCAAF-DUKE': "Duke Blue Devils",
  'NCCABB-DUQ': "Duquesne",
  'NCAAF-DUQ': "Duquesne Dukes",
  'NCAAB-DUQ': "Duquesne Dukes",
  'MLS-HOU': "Dynamo",
  'NCCABB-EIU': "E Illinois",
  'NCCABB-EKU': "E Kentucky",
  'NCCABB-EMU': "E Michigan",
  'NCCABB-EWU': "E Washington",
  'NFL-PHI': "Eagles",
  'MLS-SJ': "Earthquakes",
  'NCCABB-ECU': "East Carolina",
  'NCAAF-ECU': "East Carolina Pirates",
  'NCAAF-ETSU': "East Tennessee State Buccaneers",
  'NCAAF-EIU': "Eastern Illinois Panthers",
  'NCAAF-EMU': "Eastern Michigan Eagles",
  'NCAAB-EMU': "Eastern Michigan Eagles",
  'NCAAF-EWU': "Eastern Washington Eagles",
  'NHL-EDM': "Edmonton",
  'NCAAF-ELM': "Elmhurst",
  'NCCABB-ELON': "Elon",
  'NCCABB-EMP': "Emporiast",
  'NCCABB-EMPO': "Emporiast",
  'NCCABB-ETSU': "Etsu",
  'NCCABB-EVAN': "Evansville",
  'NCCABB-FAIR': "Fairfield",
  'NFL-ATL': "Falcons",
  'NCCABB-FAU': "Fau",
  'MLS-CIN': "Fc Cincinnati",
  'MLS-DAL': "Fc Dallas",
  'NCCABB-FLO': "Fdtc",
  'NCCABB-FDU': "Fdu",
  'NCCABB-FGCU': "Fgcu",
  'OLYMPICS-HOCKEY-MEN-FIN': "Finland",
  'OLYMPICS-HOCKEY-WOMEN-FIN': "Finland",
  'MLS-CHI': "Fire",
  'NCCABB-FIU': "Fiu",
  'NCCABB-FSC': "Flasou",
  'NCAAB-FLA': "Florida",
  'NCAAF-FLA': "Florida",
  'NCCABB-FLA': "Florida",
  'WNCAAB-FLA': "Florida",
  'NHL-FLA': "Florida",
  'NCAAB-FAMU': "Florida A&m",
  'NCCABB-FAMU': "Florida A&m",
  'WNCAAB-FAMU': "Florida A&m",
  'NCAAF-FAMU': "Florida A&m",
  'NCAAF-FAU': "Florida Atlantic Owls",
  'NCAAB-FSU': "Florida St",
  'WNCAAB-FSU': "Florida St",
  'NCAAF-FSU': "Florida St",
  'NCCABB-FSU': "Florida St",
  'NCCABB-FOR': "Fordham",
  'OLYMPICS-HOCKEY-WOMEN-FRA': "France",
  'OLYMPICS-HOCKEY-MEN-FRA': "France",
  'NCCABB-FRMN': "Francismar",
  'NCCABB-FRN': "Francismar",
  'NCCABB-FRES': "Fresno St",
  'NCAAF-FRES': "Fresno State Bulldogs",
  'NCCABB-CSUF': "Fullerton",
  'NCCABB-FUR': "Furman",
  'NCAAF-FUR': "Furman Paladins",
  'WNCAAB-GW': "G Washington",
  'NCCABB-GW': "G Washington",
  'NCAAB-GW': "G Washington",
  'NCCABB-GASO': "Ga Southern",
  'MLS-LA': "Galaxy",
  'NCCABB-GWEB': "Gardner-webb",
  'NCCABB-GMU': "George Mason",
  'WNCAAB-GTWN': "Georgetown",
  'NCAAB-GTWN': "Georgetown",
  'NCAAF-GTWN': "Georgetown",
  'NCCABB-GTWN': "Georgetown",
  'NCAAB-UGA': "Georgia",
  'NCCABB-UGA': "Georgia",
  'NCAAF-UGA': "Georgia",
  'WNCAAB-UGA': "Georgia",
  'NCAAF-GASO': "Georgia Southern Eagles",
  'NCCABB-GAST': "Georgia St",
  'NCAAF-GAST': "Georgia State Panthers",
  'NCAAB-GT': "Georgia Tech",
  'WNCAAB-GT': "Georgia Tech",
  'NCAAF-GT': "Georgia Tech",
  'NCCABB-GT': "Georgia Tech",
  'OLYMPICS-HOCKEY-MEN-GER': "Germany",
  'OLYMPICS-HOCKEY-WOMEN-GER': "Germany",
  'NFL-NYG': "Giants",
  'WNBA-GS': "Golden State",
  'NBA-GS': "Golden State",
  'NCCABB-GONZ': "Gonzaga",
  'NCAAB-GONZ': "Gonzaga Bulldogs",
  'NCCABB-GRAM': "Grambling",
  'NCAAF-GRAM': "Grambling Tigers",
  'NCCABB-GCU': "Grand Canyon",
  'NCAAB-GCU': "Grand Canyon Lopes",
  'NCCABB-GRA': "Grand View",
  'NCCABB-GB': "Green Bay",
  'NCAAF-GRI': "Grinnell",
  'NCCABB-HAMP': "Hampton",
  'NCCABB-HART': "Hartford",
  'NCCABB-HARV': "Harvard",
  'WNCAAB-HARV': "Harvard Crimson",
  'NCAAF-HAW': "Hawai'i",
  'WNCAAB-HAW': "Hawai’i",
  'NCAAB-HAW': "Hawai’i",
  'NCCABB-HAW': "Hawai’i",
  'NCCABB-HILO': "Hawaiihilo",
  'NCCABB-HPAC': "Hawaiipac",
  'NCCABB-HPU': "High Point",
  'NCCABB-HOF': "Hofstra",
  'NCCABB-HC': "Holy Cross",
  'NCCABB-HCU': "Hou Christian",
  'MLB-HOU': "Houston",
  'NCCABB-HOU': "Houston",
  'NBA-HOU': "Houston",
  'NCAAF-HOU': "Houston Cougars",
  'WNCAAB-HOU': "Houston Cougars",
  'NCAAB-HOU': "Houston Cougars",
  'NCAAB-HOW': "Howard",
  'NCAAF-HOW': "Howard",
  'WNCAAB-HOW': "Howard",
  'NCCABB-HOW': "Howard",
  'NCAAB-IDHO': "Idaho",
  'WNCAAB-IDHO': "Idaho",
  'NCCABB-IDHO': "Idaho",
  'NCAAF-IDHO': "Idaho",
  'NCCABB-IDST': "Idaho St",
  'NCAAF-IDST': "Idaho State Bengals",
  'NCCABB-ILL': "Illinois",
  'NCAAB-ILL': "Illinois Fighting Illini",
  'WNCAAB-ILL': "Illinois Fighting Illini",
  'NCAAF-ILL': "Illinois Fighting Illini",
  'NCCABB-ILST': "Illinois St",
  'MLS-MTL': "Impact",
  'NCCABB-UIW': "Incarnate Word",
  'WNBA-IND': "Indiana",
  'WNCAAB-IU': "Indiana",
  'NCCABB-IU': "Indiana",
  'NCAAB-IU': "Indiana",
  'NBA-IND': "Indiana",
  'NCAAF-IU': "Indiana Hoosiers",
  'NCCABB-INST': "Indiana St",
  'NCAAF-INST': "Indiana State Sycamores",
  'MLS-MIA': "Inter Miami Cf",
  'NCCABB-IONA': "Iona",
  'NCCABB-IOWA': "Iowa",
  'NCAAB-IOWA': "Iowa Hawkeyes",
  'WNCAAB-IOWA': "Iowa Hawkeyes",
  'NCAAF-IOWA': "Iowa Hawkeyes",
  'NCCABB-ISU': "Iowa St",
  'NCAAF-ISU': "Iowa State",
  'WNCAAB-ISU': "Iowa State",
  'NCAAB-ISU': "Iowa State",
  'OLYMPICS-HOCKEY-MEN-ITA': "Italy",
  'OLYMPICS-HOCKEY-WOMEN-ITA': "Italy",
  'NCCABB-IUIN': "Iu Indy",
  'NCAAB-IUIN': "Iu Indy",
  'WNCAAB-IUIN': "Iu Indy",
  'NCCABB-JKST': "Jackson St",
  'NCCABB-JAX': "Jacksonville",
  'NFL-JAX': "Jaguars",
  'NCCABB-JOH': "Jalc",
  'NCCABB-JMU': "James Madison",
  'NCAAF-JMU': "James Madison Dukes",
  'OLYMPICS-HOCKEY-WOMEN-JPN': "Japan",
  'WNCAAB-JXST': "Jax State",
  'NCAAF-JXST': "Jax State",
  'NCAAB-JXST': "Jax State",
  'NCCABB-JVST': "Jax State",
  'NFL-NYJ': "Jets",
  'NCCABB-KU': "Kansas",
  'NCCABB-KC': "Kansas City",
  'MLB-KC': "Kansas City",
  'NCAAB-KU': "Kansas Jayhawks",
  'WNCAAB-KU': "Kansas Jayhawks",
  'NCAAF-KU': "Kansas Jayhawks",
  'NCCABB-KSU': "Kansas St",
  'NCAAF-KSU': "Kansas State Wildcats",
  'NCAAB-KSU': "Kansas State Wildcats",
  'WNCAAB-KSU': "Kansas State Wildcats",
  'NCCABB-KENN': "Kennesaw St",
  'NCAAF-KENN': "Kennesaw State Owls",
  'NCCABB-KENT': "Kent State",
  'NCAAB-KENT': "Kent State Golden Flashes",
  'NCAAF-KENT': "Kent State Golden Flashes",
  'NCCABB-UK': "Kentucky",
  'NCAAB-UK': "Kentucky",
  'WNCAAB-UK': "Kentucky",
  'NCAAF-UK': "Kentucky Wildcats",
  'NBA-LAC': "La",
  'NCCABB-LAS': "La Salle",
  'NCCABB-LCO': "Lacollege",
  'NCCABB-LOUC': "Lacollege",
  'NCCABB-LAF': "Lafayette",
  'NCAAF-LAF': "Lafayette Leopards",
  'MLS-LAFC': "Lafc",
  'NCCABB-LAM': "Lamar",
  'WNBA-LV': "Las Vegas",
  'OLYMPICS-HOCKEY-MEN-LAT': "Latvia",
  'NCCABB-LEM': "Le Moyne",
  'NCCABB-LEH': "Lehigh",
  'NCCABB-LEN': "Lenrhyne",
  'NCCABB-LENR': "Lenrhyne",
  'NCCABB-LIB': "Liberty",
  'NCCABB-LINC': "Lincoln",
  'NCCABB-LNC': "Lincoln",
  'NCCABB-LIN': "Linfield",
  'NFL-DET': "Lions",
  'NCCABB-LIP': "Lipscomb",
  'NCCABB-LR': "Little Rock",
  'NCCABB-LMU': "Lmu",
  'NCCABB-LBSU': "Long Beach St",
  'NCCABB-LIU': "Long Island",
  'NCAAF-LIU': "Long Island University Sharks",
  'NCCABB-LONG': "Longwood",
  'NCCABB-LOR': "Loras College",
  'MLB-LAA': "Los Angeles",
  'MLB-LAD': "Los Angeles",
  'NHL-LA': "Los Angeles",
  'NBA-LAL': "Los Angeles",
  'WNBA-LA': "Los Angeles",
  'NCCABB-UL': "Louisiana",
  'NCAAF-UL': "Louisiana Ragin' Cajuns",
  'NCCABB-LT': "Louisiana Tech",
  'NCAAF-LT': "Louisiana Tech Bulldogs",
  'NCCABB-LOU': "Louisville",
  'NCAAB-LOU': "Louisville",
  'WNCAAB-LOU': "Louisville",
  'NCAAF-LOU': "Louisville Cardinals",
  'NCCABB-LUC': "Loyola Chicago",
  'NCAAB-LMU': "Loyola Marymount Lions",
  'NCCABB-L-MD': "Loyola Md",
  'NCCABB-LSU': "Lsu",
  'NCAAF-LSU': "Lsu Tigers",
  'WNCAAB-LSU': "Lsu Tigers",
  'NCAAB-LSU': "Lsu Tigers",
  'NCCABB-LUBC': "Lubbchrist",
  'NCAAF-LUT': "Luther",
  'NCCABB-ME': "Maine",
  'NCAAF-ME': "Maine Black Bears",
  'NCCABB-MAN': "Manhattan",
  'NCCABB-MRST': "Marist",
  'NCCABB-MARQ': "Marquette",
  'NCAAB-MARQ': "Marquette Golden Eagles",
  'NCCABB-MRSH': "Marshall",
  'NCAAF-MRSH': "Marshall Thundering Herd",
  'NCCABB-MD': "Maryland",
  'NCAAF-MD': "Maryland Terrapins",
  'WNCAAB-MD': "Maryland Terrapins",
  'NCAAB-MD': "Maryland Terrapins",
  'NCAAB-MASS': "Massachusetts Minutemen",
  'NCAAF-MASS': "Massachusetts Minutemen",
  'NCCABB-MCA': "Mca",
  'NCCABB-MACU': "Mca",
  'NCCABB-MCN': "Mcneese",
  'NCCABB-UMES': "Md Eastern",
  'NBA-MEM': "Memphis",
  'NCCABB-MEM': "Memphis",
  'NCAAF-MEM': "Memphis Tigers",
  'NCAAF-MER': "Mercer Bears",
  'NCCABB-MER': "Mercyhurst",
  'NCCABB-MRMK': "Merrimack",
  'NBA-MIA': "Miami",
  'NCCABB-MIA': "Miami",
  'MLB-MIA': "Miami",
  'NCAAB-M-OH': "Miami (OH) Redhawks",
  'NCAAF-M-OH': "Miami (OH) Redhawks",
  'WNCAAB-MIA': "Miami Hurricanes",
  'NCAAB-MIA': "Miami Hurricanes",
  'NCAAF-MIA': "Miami Hurricanes",
  'NCCABB-M-OH': "Miami Oh",
  'NCCABB-MICH': "Michigan",
  'NCCABB-MSU': "Michigan St",
  'WNCAAB-MSU': "Michigan State Spartans",
  'NCAAF-MSU': "Michigan State Spartans",
  'NCAAB-MSU': "Michigan State Spartans",
  'NCAAB-MICH': "Michigan Wolverines",
  'WNCAAB-MICH': "Michigan Wolverines",
  'NCAAF-MICH': "Michigan Wolverines",
  'NCAAF-MIL': "Millikin",
  'MLB-MIL': "Milwaukee",
  'NBA-MIL': "Milwaukee",
  'NCCABB-MILW': "Milwaukee",
  'NCCABB-MINN': "Minnesota",
  'WNBA-MIN': "Minnesota",
  'NBA-MIN': "Minnesota",
  'MLB-MIN': "Minnesota",
  'NHL-MIN': "Minnesota",
  'PWHL-MIN': "Minnesota Frost",
  'NCAAB-MINN': "Minnesota Golden Gophers",
  'WNCAAB-MINN': "Minnesota Golden Gophers",
  'NCAAF-MINN': "Minnesota Golden Gophers",
  'MLS-MIN': "Minnesota United Fc",
  'NCCABB-MVSU': "Miss Valley St",
  'NCCABB-MSST': "Mississippi St",
  'WNCAAB-MSST': "Mississippi State Bulldogs",
  'NCAAF-MSST': "Mississippi State Bulldogs",
  'NCAAB-MSST': "Mississippi State Bulldogs",
  'NCCABB-MIZ': "Missouri",
  'NCCABB-MOST': "Missouri St",
  'NCAAF-MOST': "Missouri State Bears",
  'NCAAF-MIZ': "Missouri Tigers",
  'WNCAAB-MIZ': "Missouri Tigers",
  'NCAAB-MIZ': "Missouri Tigers",
  'NCCABB-MONM': "Monmouth",
  'NCCABB-MONT': "Montana",
  'NCAAF-MONT': "Montana Grizzlies",
  'NCCABB-MTST': "Montana St",
  'NHL-MTL': "Montreal",
  'PWHL-MTL': "Montréal Victoire",
  'NCCABB-MORE': "Morehead St",
  'NCAAF-MOR': "Morehouse",
  'NCCABB-MORG': "Morgan St",
  'NCAAF-MORG': "Morgan State Bears",
  'NCCABB-MSM': "Mount St Marys",
  'NCCABB-MTSU': "Mtsu",
  'WNCAAB-MUR': "Murray St",
  'NCAAB-MUR': "Murray St",
  'NCCABB-MUR': "Murray St",
  'NCAAF-MUR': "Murray State Racers",
  'NCCABB-NAU': "N Arizona",
  'NCCABB-UNCO': "N Colorado",
  'NCCABB-NDSU': "N Dakota St",
  'NCCABB-NIU': "N Illinois",
  'NCAAB-NKU': "N Kentucky",
  'WNCAAB-NKU': "N Kentucky",
  'NCCABB-NKU': "N Kentucky",
  'NCCABB-NWST': "N'western St",
  'NHL-NSH': "Nashville",
  'MLS-NSH': "Nashville Sc",
  'NCCABB-NAVY': "Navy",
  'NCAAF-NAVY': "Navy Midshipmen",
  'NCCABB-NCAT': "Nc A&t",
  'NCCABB-NCCU': "Nc Central",
  'NCCABB-NCSU': "Nc State",
  'WNCAAB-NCSU': "Nc State Wolfpack",
  'NCAAB-NCSU': "Nc State Wolfpack",
  'NCAAF-NCSU': "Nc State Wolfpack",
  'NCCABB-NK': "Neb Kearney",
  'NCCABB-NBKE': "Neb Kearney",
  'NCCABB-NEB': "Nebraska",
  'NCAAF-NEB': "Nebraska Cornhuskers",
  'WNCAAB-NEB': "Nebraska Cornhuskers",
  'NCAAB-NEB': "Nebraska Cornhuskers",
  'NCCABB-NEV': "Nevada",
  'NCAAB-NEV': "Nevada Wolf Pack",
  'NCCABB-UNH': "New Hampshire",
  'NCAAF-UNH': "New Hampshire Wildcats",
  'NCCABB-NHVN': "New Haven Chargers",
  'NHL-NJ': "New Jersey",
  'NCCABB-UNM': "New Mexico",
  'NCAAF-UNM': "New Mexico Lobos",
  'NCCABB-NMSU': "New Mexico St",
  'NCAAF-NMSU': "New Mexico State Aggies",
  'NBA-NO': "New Orleans",
  'NCCABB-UNO': "New Orleans",
  'NHL-NYI': "New York",
  'NBA-NY': "New York",
  'WNBA-NY': "New York",
  'MLB-NYM': "New York",
  'NHL-NYR': "New York",
  'MLB-NYY': "New York",
  'PWHL-NY': "New York Sirens",
  'NCCABB-NIA': "Niagara",
  'NCCABB-NICH': "Nicholls",
  'NCAAF-NICH': "Nicholls Colonels",
  'NCCABB-NJIT': "Njit",
  'NCCABB-NOR': "Nmcc",
  'NCCABB-NORF': "Norfolk St",
  'NCAAF-NORF': "Norfolk State Spartans",
  'NCCABB-NTGA': "Norge",
  'NCCABB-NGA': "Norge",
  'NCCABB-UNA': "North Alabama",
  'NCAAF-UNA': "North Alabama Lions",
  'NCCABB-UNC': "North Carolina",
  'NCAAF-UNC': "North Carolina Tar Heels",
  'NCAAB-UNC': "North Carolina Tar Heels",
  'WNCAAB-UNC': "North Carolina Tar Heels",
  'NCCABB-UND': "North Dakota",
  'NCAAF-UND': "North Dakota Fighting Hawks",
  'NCCABB-UNF': "North Florida",
  'NCAAF-NOR': "North Park",
  'NCCABB-UNT': "North Texas",
  'NCAAF-UNT': "North Texas Mean Green",
  'NCCABB-NE': "Northeastern",
  'NCAAF-NAU': "Northern Arizona Lumberjacks",
  'NCAAB-NIU': "Northern Illinois Huskies",
  'NCAAF-NIU': "Northern Illinois Huskies",
  'NCCABB-UNI': "Northern Iowa",
  'NCAAF-UNI': "Northern Iowa Panthers",
  'NCAAB-NU': "Northwestern",
  'WNCAAB-NU': "Northwestern",
  'NCCABB-NU': "Northwestern",
  'NCAAF-NU': "Northwestern Wildcats",
  'NCAAB-ND': "Notre Dame",
  'WNCAAB-ND': "Notre Dame",
  'NCCABB-ND': "Notre Dame",
  'NCAAF-ND': "Notre Dame Fighting Irish",
  'NCCABB-NOV': "Novase",
  'NCCABB-NWIA': "Nwcolliowa",
  'MLS-NYC': "Nyc Fc",
  'NCCABB-NYIT': "Nyit",
  'NCCABB-OAK': "Oakland",
  'NCCABB-OHIO': "Ohio",
  'NCAAF-OHIO': "Ohio Bobcats",
  'NCCABB-OSU': "Ohio State",
  'WNCAAB-OSU': "Ohio State Buckeyes",
  'NCAAF-OSU': "Ohio State Buckeyes",
  'NCAAB-OSU': "Ohio State Buckeyes",
  'NCCABB-OU': "Oklahoma",
  'NBA-OKC': "Oklahoma City",
  'WNCAAB-OU': "Oklahoma Sooners",
  'NCAAB-OU': "Oklahoma Sooners",
  'NCAAF-OU': "Oklahoma Sooners",
  'NCCABB-OKST': "Oklahoma St",
  'NCAAB-OKST': "Oklahoma State Cowboys",
  'NCAAF-OKST': "Oklahoma State Cowboys",
  'WNCAAB-OKST': "Oklahoma State Cowgirls",
  'NCCABB-ODU': "Old Dominion",
  'NCAAF-ODU': "Old Dominion Monarchs",
  'NCCABB-MISS': "Ole Miss",
  'NCAAB-MISS': "Ole Miss Rebels",
  'WNCAAB-MISS': "Ole Miss Rebels",
  'NCAAF-MISS': "Ole Miss Rebels",
  'NCCABB-OMA': "Omaha",
  'NCCABB-ORU': "Oral Roberts",
  'NCCABB-ORE': "Oregon",
  'NCAAB-ORE': "Oregon Ducks",
  'WNCAAB-ORE': "Oregon Ducks",
  'NCAAF-ORE': "Oregon Ducks",
  'NCCABB-ORST': "Oregon St",
  'NCAAF-ORST': "Oregon State Beavers",
  'NBA-ORL': "Orlando",
  'MLS-ORL': "Orlando City Sc",
  'NHL-OTT': "Ottawa",
  'PWHL-OTT': "Ottawa Charge",
  'NCCABB-PAC': "Pacific",
  'NFL-GB': "Packers",
  'NFL-CAR': "Panthers",
  'NFL-NE': "Patriots",
  'NCCABB-PEA': "Pearl",
  'NCCABB-PENN': "Penn",
  'NCCABB-PSU': "Penn State",
  'WNCAAB-PSU': "Penn State Lady Lions",
  'NCAAF-PSU': "Penn State Nittany Lions",
  'NCAAB-PSU': "Penn State Nittany Lions",
  'WNCAAB-PENN': "Pennsylvania Quakers",
  'NCCABB-PEPP': "Pepperdine",
  'NCAAB-PEPP': "Pepperdine Waves",
  'NBA-PHI': "Philadelphia",
  'NHL-PHI': "Philadelphia",
  'MLB-PHI': "Philadelphia",
  'WNBA-PHX': "Phoenix",
  'NBA-PHX': "Phoenix",
  'NCCABB-PITT': "Pitt",
  'NHL-PIT': "Pittsburgh",
  'MLB-PIT': "Pittsburgh",
  'NCAAB-PITT': "Pittsburgh Panthers",
  'NCAAF-PITT': "Pittsburgh Panthers",
  'WNCAAB-PITT': "Pittsburgh Panthers",
  'WNBA-POR': "Portland",
  'NCCABB-PORT': "Portland",
  'NBA-POR': "Portland",
  'NCAAB-PORT': "Portland Pilots",
  'NCCABB-PRST': "Portland St",
  'NCAAF-PRST': "Portland State Vikings",
  'NCCABB-PV': "Prairie View",
  'NCAAF-PV': "Prairie View A&m Panthers",
  'NCCABB-PRES': "Presbyterian",
  'NCCABB-PRIN': "Princeton",
  'WNCAAB-PRIN': "Princeton Tigers",
  'NCCABB-PROV': "Providence",
  'NCAAB-PROV': "Providence Friars",
  'WNCAAB-PROV': "Providence Friars",
  'NCCABB-PUR': "Purdue",
  'NCAAF-PUR': "Purdue Boilermakers",
  'WNCAAB-PUR': "Purdue Boilermakers",
  'NCAAB-PUR': "Purdue Boilermakers",
  'NCCABB-PFW': "Purdue Fw",
  'NCCABB-QUOC': "Queens",
  'NCCABB-QUIN': "Quinnipiac",
  'NCCABB-RAD': "Radford",
  'NFL-LV': "Raiders",
  'NFL-LAR': "Rams",
  'MLS-COL': "Rapids",
  'NFL-BAL': "Ravens",
  'MLS-RSL': "Real Salt Lake",
  'MLS-NY': "Red Bulls",
  'NCAAF-RED': "Redlands",
  'MLS-NE': "Revolution",
  'NCCABB-URI': "Rhode Island",
  'NCCABB-RICE': "Rice",
  'NCAAF-RICE': "Rice Owls",
  'NCCABB-RICH': "Richmond",
  'NCAAF-RICH': "Richmond Spiders",
  'NCCABB-RID': "Rider",
  'NCCABB-RMU': "Robert Morris",
  'NCCABB-ROO': "Roosevelt",
  'NCCABB-RUTG': "Rutgers",
  'NCAAF-RUTG': "Rutgers Scarlet Knights",
  'NCAAB-RUTG': "Rutgers Scarlet Knights",
  'WNCAAB-RUTG': "Rutgers Scarlet Knights",
  'NCCABB-SDST': "S Dakota St",
  'WNCAAB-SIU': "S Illinois",
  'NCCABB-SIU': "S Illinois",
  'NCAAB-SIU': "S Illinois",
  'NBA-SAC': "Sacramento",
  'NCAAF-SAC': "Sacramento St",
  'WNCAAB-SAC': "Sacramento St",
  'NCCABB-SAC': "Sacramento St",
  'NCAAB-SAC': "Sacramento St",
  'NCCABB-SHU': "Sacred Heart",
  'NCCABB-SFPA': "Saint Francis",
  'NCCABB-JOES': "Saint Joseph's",
  'NCCABB-SLU': "Saint Louis",
  'NCAAB-SLU': "Saint Louis Billikens",
  'NCCABB-SMC': "Saint Mary's",
  'NCAAB-SMC': "Saint Mary's Gaels",
  'NCCABB-SPU': "Saint Peter's",
  'NFL-NO': "Saints",
  'NCCABB-SSU': "Salisbury",
  'NCCABB-SALB': "Salisbury",
  'NCCABB-SHSU': "Sam Houston",
  'NCAAF-SHSU': "Sam Houston Bearkats",
  'NCCABB-SAM': "Samford",
  'NBA-SA': "San Antonio",
  'MLB-SD': "San Diego",
  'NCCABB-USD': "San Diego",
  'MLS-SD': "San Diego Fc",
  'NCCABB-SDSU': "San Diego St",
  'NCAAF-SDSU': "San Diego St",
  'NCAAB-SDSU': "San Diego St",
  'WNCAAB-SDSU': "San Diego St",
  'NCCABB-SF': "San Francisco",
  'MLB-SF': "San Francisco",
  'NCAAB-SF': "San Francisco Dons",
  'NHL-SJ': "San Jose",
  'NCAAB-SJSU': "San José St",
  'NCAAF-SJSU': "San José St",
  'NCCABB-SJSU': "San José St",
  'WNCAAB-SJSU': "San José St",
  'NCCABB-SAN': "Sanjacjc",
  'NCCABB-UCSB': "Santa Barbara",
  'NCCABB-SCU': "Santa Clara",
  'NCAAB-SCU': "Santa Clara Broncos",
  'NCCABB-SAVS': "Savannah St",
  'NCCABB-SAV': "Savannah St",
  'NCCABB-SCST': "Sc State",
  'NCCABB-SCUP': "Sc Upstate",
  'NCCABB-UPST': "Sc Upstate",
  'NCCABB-STA': "Scof",
  'NCCABB-SELA': "Se Louisiana",
  'NCCABB-SEMO': "Se Missouri",
  'NFL-SEA': "Seahawks",
  'NHL-SEA': "Seattle",
  'MLB-SEA': "Seattle",
  'WNBA-SEA': "Seattle",
  'PWHL-SEA': "Seattle Torrent",
  'NCCABB-SEA': "Seattle U",
  'NCAAB-SEA': "Seattle U Redhawks",
  'NCCABB-HALL': "Seton Hall",
  'WNCAAB-HALL': "Seton Hall Pirates",
  'NCAAB-HALL': "Seton Hall Pirates",
  'NCCABB-SFA': "Sf Austin",
  'NCCABB-SIE': "Siena",
  'NCCABB-SIUE': "Siue",
  'OLYMPICS-HOCKEY-MEN-SVK': "Slovakia",
  'NCCABB-SMU': "Smu",
  'NCAAB-SMU': "Smu Mustangs",
  'NCAAF-SMU': "Smu Mustangs",
  'WNCAAB-SMU': "Smu Mustangs",
  'NCCABB-USI': "So Indiana",
  'WNCAAB-USI': "So Indiana",
  'MLS-SEA': "Sounders",
  'WNCAAB-USA': "South Alabama",
  'NCCABB-USA': "South Alabama",
  'NCAAB-USA': "South Alabama",
  'NCAAF-USA': "South Alabama",
  'NCCABB-SC': "South Carolina",
  'WNCAAB-SC': "South Carolina Gamecocks",
  'NCAAB-SC': "South Carolina Gamecocks",
  'NCAAF-SC': "South Carolina Gamecocks",
  'NCCABB-SDAK': "South Dakota",
  'NCAAF-SDAK': "South Dakota Coyotes",
  'NCAAF-SDST': "South Dakota State Jackrabbits",
  'WNCAAB-USF': "South Florida",
  'NCCABB-USF': "South Florida",
  'NCAAB-USF': "South Florida",
  'NCAAF-USF': "South Florida",
  'NCAAF-SEMO': "Southeast Missouri State Redhawks",
  'NCAAF-SIU': "Southern Illinois Salukis",
  'NCAAF-SOU': "Southern Jaguars",
  'NCCABB-USM': "Southern Miss",
  'NCAAF-USM': "Southern Miss Golden Eagles",
  'NCCABB-SUU': "Southern Utah",
  'NCAAF-SUU': "Southern Utah Thunderbirds",
  'NCCABB-SOU': "Southwest",
  'MLS-SKC': "Sporting",
  'NCCABB-SBU': "St Bonaventure",
  'NCCABB-SFBK': "St Francis Bk",
  'NCCABB-STGR': "St Gregorys",
  'NCCABB-SJU': "St John's",
  'NCCABB-STMN': "St Thomas (MN)",
  'NCAAB-SBU': "St. Bonaventure Bonnies",
  'WNCAAB-SJU': "St. John's Red Storm",
  'NCAAB-SJU': "St. John's Red Storm",
  'NHL-STL': "St. Louis",
  'MLB-STL': "St. Louis",
  'MLS-STL': "St. Louis City Sc",
  'NCCABB-ST.': "St. Olaf",
  'NCAAF-STAN': "Stanford",
  'WNCAAB-STAN': "Stanford",
  'NCAAB-STAN': "Stanford",
  'NCCABB-STAN': "Stanford",
  'NFL-PIT': "Steelers",
  'NCCABB-STET': "Stetson",
  'NCAAF-STET': "Stetson",
  'WNCAAB-STET': "Stetson",
  'NCAAB-STET': "Stetson",
  'NCCABB-STMT': "Stmartins",
  'NCCABB-SM': "Stmartins",
  'NCCABB-STO': "Stonehill",
  'NCCABB-STBK': "Stony Brook",
  'NCCABB-STFL': "Stthom(fl)",
  'OLYMPICS-HOCKEY-WOMEN-SWE': "Sweden",
  'OLYMPICS-HOCKEY-MEN-SWE': "Sweden",
  'OLYMPICS-HOCKEY-MEN-SUI': "Switzerland",
  'OLYMPICS-HOCKEY-WOMEN-SUI': "Switzerland",
  'NCCABB-SWOS': "Swoklast",
  'NCCABB-SYR': "Syracuse",
  'NCAAB-SYR': "Syracuse Orange",
  'NCAAF-SYR': "Syracuse Orange",
  'NCCABB-TABR': "Tabor",
  'NCCABB-TAB': "Tabor",
  'NHL-TB': "Tampa Bay",
  'MLB-TB': "Tampa Bay",
  'NCCABB-TAR': "Tarleton St",
  'NCCABB-TBD': "Tbd",
  'NCCABB-TCU': "Tcu",
  'NCAAF-TCU': "Tcu Horned Frogs",
  'NCAAB-TCU': "Tcu Horned Frogs",
  'WNCAAB-TCU': "Tcu Horned Frogs",
  'NCCABB-TEM': "Temple",
  'NCAAF-TEM': "Temple Owls",
  'NCCABB-TENN': "Tennessee",
  'WNCAAB-TENN': "Tennessee Lady Volunteers",
  'NCCABB-TNST': "Tennessee St",
  'NCAAF-TNST': "Tennessee State Tigers",
  'NCCABB-TNTC': "Tennessee Tech",
  'NCAAF-TENN': "Tennessee Volunteers",
  'NCAAB-TENN': "Tennessee Volunteers",
  'NFL-HOU': "Texans",
  'NCCABB-TEX': "Texas",
  'MLB-TEX': "Texas",
  'NCCABB-TA&M': "Texas A&m",
  'NCAAB-TA&M': "Texas A&m Aggies",
  'WNCAAB-TA&M': "Texas A&m Aggies",
  'NCAAF-TA&M': "Texas A&m Aggies",
  'NCCABB-AMCC': "Texas A&m-cc",
  'WNCAAB-TEX': "Texas Longhorns",
  'NCAAB-TEX': "Texas Longhorns",
  'NCAAF-TEX': "Texas Longhorns",
  'NCCABB-TL': "Texas Lutheran",
  'NCCABB-TXSO': "Texas Southern",
  'NCCABB-TXST': "Texas St",
  'NCAAF-TXST': "Texas State Bobcats",
  'NCCABB-TTU': "Texas Tech",
  'WNCAAB-TTU': "Texas Tech Lady Raiders",
  'NCAAF-TTU': "Texas Tech Red Raiders",
  'NCAAB-TTU': "Texas Tech Red Raiders",
  'NCCABB-CIT': "The Citadel",
  'MLS-POR': "Timbers",
  'NFL-TEN': "Titans",
  'NCCABB-TOL': "Toledo",
  'NCAAF-TOL': "Toledo Rockets",
  'MLB-TOR': "Toronto",
  'NHL-TOR': "Toronto",
  'NBA-TOR': "Toronto",
  'WNBA-TOR': "Toronto",
  'MLS-TOR': "Toronto Fc",
  'PWHL-TOR': "Toronto Sceptres",
  'NCCABB-TOW': "Towson",
  'NCAAF-TOW': "Towson Tigers",
  'NCCABB-TROY': "Troy",
  'NCAAF-TROY': "Troy Trojans",
  'NCCABB-TRST': "Truman St",
  'NCCABB-TULN': "Tulane",
  'NCAAF-TULN': "Tulane Green Wave",
  'NCCABB-TLSA': "Tulsa",
  'NCAAF-TLSA': "Tulsa Golden Hurricane",
  'NCCABB-UTPA': "Tx-pan American",
  'WNCAAB-UAB': "Uab",
  'NCAAF-UAB': "Uab",
  'NCCABB-UAB': "Uab",
  'NCAAB-UAB': "Uab",
  'NCCABB-ALB': "Ualbany",
  'NCCABB-UCD': "Uc Davis",
  'NCAAF-UCD': "Uc Davis Aggies",
  'NCCABB-UCI': "Uc Irvine",
  'NCCABB-UCR': "Uc Riverside",
  'NCAAB-UCR': "Uc Riverside",
  'WNCAAB-UCR': "Uc Riverside",
  'NCCABB-UCSD': "Uc San Diego",
  'WNCAAB-UCSD': "Uc San Diego",
  'NCAAB-UCSD': "Uc San Diego",
  'NCCABB-UCF': "Ucf",
  'NCAAF-UCF': "Ucf Knights",
  'WNCAAB-UCF': "Ucf Knights",
  'NCAAB-UCF': "Ucf Knights",
  'NCCABB-UCLA': "Ucla",
  'NCAAB-UCLA': "Ucla",
  'WNCAAB-UCLA': "Ucla",
  'NCAAF-UCLA': "Ucla",
  'WNCAAB-CONN': "Uconn",
  'NCAAF-CONN': "Uconn",
  'NCCABB-CONN': "Uconn",
  'NCAAB-CONN': "Uconn",
  'WNCAAB-UIC': "Uic",
  'NCAAB-UIC': "Uic",
  'NCCABB-UIC': "Uic",
  'NCCABB-ULM': "Ul Monroe",
  'NCAAF-ULM': "Ul Monroe Warhawks",
  'NCCABB-MASS': "Umass",
  'NCCABB-UML': "Umass Lowell",
  'NCCABB-UMBC': "Umbc",
  'NCCABB-UNCA': "Unc Asheville",
  'NCCABB-UNCG': "Unc Greensboro",
  'NCCABB-UNCW': "Unc Wilmington",
  'MLS-PHI': "Union",
  'MLS-DC': "United",
  'OLYMPICS-HOCKEY-WOMEN-USA': "United States",
  'OLYMPICS-HOCKEY-MEN-USA': "United States",
  'NCCABB-TAM': "Univtampa",
  'NCCABB-UNLV': "Unlv",
  'NCCABB-UPP': "Upper Iowa",
  'NCAAF-USC': "Usc",
  'NCAAB-USC': "Usc",
  'NCCABB-USC': "Usc",
  'WNCAAB-USC': "Usc",
  'NCCABB-UTA': "Ut Arlington",
  'NCCABB-UTM': "Ut Martin",
  'NCAAF-UTM': "Ut Martin Skyhawks",
  'NCCABB-RGV': "Ut Rio Grande",
  'NBA-UTAH': "Utah",
  'NHL-UTA': "Utah",
  'NCCABB-UTAH': "Utah",
  'NCCABB-USU': "Utah State",
  'NCAAB-USU': "Utah State Aggies",
  'NCAAF-USU': "Utah State Aggies",
  'NCCABB-UTU': "Utah Tech",
  'NCAAF-UTU': "Utah Tech Trailblazers",
  'NCAAF-UTAH': "Utah Utes",
  'WNCAAB-UTAH': "Utah Utes",
  'NCAAB-UTAH': "Utah Utes",
  'NCCABB-UVU': "Utah Valley",
  'NCCABB-UTEP': "Utep",
  'NCAAF-UTEP': "Utep Miners",
  'NCCABB-UTSA': "Utsa",
  'NCAAF-UTSA': "Utsa Roadrunners",
  'NCCABB-UWP': "Uw-platteville",
  'NCCABB-VALD': "Valdosta",
  'NCCABB-VAL': "Valparaiso",
  'NHL-VAN': "Vancouver",
  'PWHL-VAN': "Vancouver Goldeneyes",
  'NCCABB-VAN': "Vanderbilt",
  'NCAAF-VAN': "Vanderbilt Commodores",
  'WNCAAB-VAN': "Vanderbilt Commodores",
  'NCAAB-VAN': "Vanderbilt Commodores",
  'NCCABB-VCU': "Vcu",
  'NHL-VGK': "Vegas",
  'NCCABB-UVM': "Vermont",
  'NFL-MIN': "Vikings",
  'NCCABB-VILL': "Villanova",
  'NCAAF-VILL': "Villanova Wildcats",
  'NCAAB-VILL': "Villanova Wildcats",
  'WNCAAB-VILL': "Villanova Wildcats",
  'NCCABB-UVA': "Virginia",
  'NCAAB-UVA': "Virginia Cavaliers",
  'WNCAAB-UVA': "Virginia Cavaliers",
  'NCAAF-UVA': "Virginia Cavaliers",
  'NCCABB-VT': "Virginia Tech",
  'NCAAF-VT': "Virginia Tech Hokies",
  'WNCAAB-VT': "Virginia Tech Hokies",
  'NCAAB-VT': "Virginia Tech Hokies",
  'NCCABB-VMI': "Vmi",
  'NCAAF-VMI': "Vmi Keydets",
  'NCCABB-WCU': "W Carolina",
  'NCCABB-WIU': "W Illinois",
  'NCCABB-WMU': "W Michigan",
  'NCCABB-WAG': "Wagner",
  'NCAAF-WAG': "Wagner Seahawks",
  'NCCABB-WAKE': "Wake Forest",
  'WNCAAB-WAKE': "Wake Forest Demon Deacons",
  'NCAAB-WAKE': "Wake Forest Demon Deacons",
  'NCAAF-WAKE': "Wake Forest Demon Deacons",
  'NCCABB-WAR': "Wartburg",
  'NCCABB-129755': "Waseda University Waseda Uni",
  'NHL-WSH': "Washington",
  'NCCABB-WASH': "Washington",
  'WNBA-WSH': "Washington",
  'MLB-WSH': "Washington",
  'NBA-WSH': "Washington",
  'NCAAB-WASH': "Washington Huskies",
  'NCAAF-WASH': "Washington Huskies",
  'WNCAAB-WASH': "Washington Huskies",
  'NCCABB-WSU': "Washington St",
  'NCAAB-WSU': "Washington State Cougars",
  'NCAAF-WSU': "Washington State Cougars",
  'NCCABB-WNST': "Waynestne",
  'NCCABB-WAY': "Waynestne",
  'NCCABB-WEB': "Weber St",
  'NCAAF-WEB': "Weber State Wildcats",
  'NCCABB-WES': "West Georgia",
  'NCCABB-WVU': "West Virginia",
  'NCAAF-WVU': "West Virginia Mountaineers",
  'WNCAAB-WVU': "West Virginia Mountaineers",
  'NCAAB-WVU': "West Virginia Mountaineers",
  'NCAAF-WCU': "Western Carolina Catamounts",
  'NCAAF-WIU': "Western Illinois Leathernecks",
  'NCAAF-WKU': "Western Kentucky Hilltoppers",
  'NCCABB-WKU': "Western Ky",
  'NCAAB-WKU': "Western Ky",
  'NCAAB-WMU': "Western Michigan Broncos",
  'NCAAF-WMU': "Western Michigan Broncos",
  'MLS-VAN': "Whitecaps",
  'NCCABB-WICH': "Wichita St",
  'NCCABB-W&M': "William & Mary",
  'NCCABB-WILL': "Williamwds",
  'NCCABB-WIL': "Williamwds",
  'NHL-WPG': "Winnipeg",
  'NCCABB-WIN': "Winthrop",
  'NCCABB-WIS': "Wisconsin",
  'NCAAF-WIS': "Wisconsin Badgers",
  'WNCAAB-WIS': "Wisconsin Badgers",
  'NCAAB-WIS': "Wisconsin Badgers",
  'NCCABB-WOF': "Wofford",
  'NCCABB-WRST': "Wright St",
  'NCCABB-WYO': "Wyoming",
  'NCAAF-WYO': "Wyoming Cowboys",
  'NCCABB-XAV': "Xavier",
  'WNCAAB-XAV': "Xavier Musketeers",
  'NCAAB-XAV': "Xavier Musketeers",
  'NCAAF-YALE': "Yale",
  'NCCABB-YALE': "Yale",
  'NCAAB-YALE': "Yale",
  'WNCAAB-YALE': "Yale",
  'NCCABB-YSU': "Youngstown St",
  'NCAAF-YSU': "Youngstown State Penguins",
};
