export const TeamsEnum: Record<string, string> = {
  'NCAAF-ACU': 'Abilene Christian Wildcats',
  'NCCABB-ACU': 'Abilene Christian Wildcats',
  'NCCABB-AFA': 'Air Force Falcons',
  'NCAAF-AKR': 'Akron Zips',
  'NCCABB-AKR': 'Akron Zips',
  'NCCABB-AAMU': 'Alabama A&m Bulldogs',
  'WNCAAB-ALA': 'Alabama Crimson Tide',
  'NCCABB-ALA': 'Alabama Crimson Tide',
  'NCAAB-ALA': 'Alabama Crimson Tide',
  'NCAAF-ALA': 'Alabama Crimson Tide',
  'NCCABB-ALST': 'Alabama State Hornets',
  'NCCABB-ALCN': 'Alcorn State Braves',
  'NCCABB-ALMA': 'Alma Scots',
  'WNCAAB-AMER': 'American University Eagles',
  'NCAAB-AMER': 'American University Eagles',
  'NCCABB-AMER': 'American University Eagles',
  'NCAAF-AMH': 'Amherst Mammoths',
  'NHL-ANA': 'Anaheim Ducks',
  'NCCABB-ANDC': 'Anderson (IN) Ravens',
  'NCAAF-ANN': 'Anna Maria College Amcats',
  'NCAAF-APP': 'App State Mountaineers',
  'NCCABB-APP': 'App State Mountaineers',
  'NFL-ARI': 'Arizona Cardinals',
  'MLB-ARI': 'Arizona Diamondbacks',
  'NCCABB-ASU': 'Arizona State Sun Devils',
  'NCAAB-ASU': 'Arizona State Sun Devils',
  'WNCAAB-ASU': 'Arizona State Sun Devils',
  'NCAAF-ASU': 'Arizona State Sun Devils',
  'NCCABB-ARIZ': 'Arizona Wildcats',
  'NCAAB-ARIZ': 'Arizona Wildcats',
  'WNCAAB-ARIZ': 'Arizona Wildcats',
  'NCAAF-ARIZ': 'Arizona Wildcats',
  'NCCABB-ARK': 'Arkansas Razorbacks',
  'NCAAB-ARK': 'Arkansas Razorbacks',
  'WNCAAB-ARK': 'Arkansas Razorbacks',
  'NCAAF-ARK': 'Arkansas Razorbacks',
  'NCCABB-ARST': 'Arkansas State Red Wolves',
  'NCAAF-ARST': 'Arkansas State Red Wolves',
  'NCCABB-UAPB': 'Arkansas-pine Bluff Golden Lions',
  'NCAAF-UAPB': 'Arkansas-pine Bluff Golden Lions',
  'NCCABB-ARMY': 'Army Black Knights',
  'MLB-ATH': 'Athletics',
  'MLB-ATL': 'Atlanta Braves',
  'WNBA-ATL': 'Atlanta Dream',
  'NFL-ATL': 'Atlanta Falcons',
  'NBA-ATL': 'Atlanta Hawks',
  'MLS-ATL': 'Atlanta United Fc',
  'WNCAAB-AUB': 'Auburn Tigers',
  'NCAAF-AUB': 'Auburn Tigers',
  'NCAAB-AUB': 'Auburn Tigers',
  'NCCABB-AUB': 'Auburn Tigers',
  'NCCABB-AUG': 'Augustana College (Il) Vikings',
  'NCCABB-AUR': 'Aurora Spartans',
  'MLS-ATX': 'Austin Fc',
  'NCCABB-APSU': 'Austin Peay Governors',
  'NCAAF-APSU': 'Austin Peay Governors',
  'NCCABB-BAKE': 'Baker University',
  'NCCABB-BALL': 'Ball State Cardinals',
  'NCAAF-BALL': 'Ball State Cardinals',
  'MLB-BAL': 'Baltimore Orioles',
  'NFL-BAL': 'Baltimore Ravens',
  'NCCABB-BAR': 'Barry Buccaneers',
  'NCAAF-BAY': 'Baylor Bears',
  'NCCABB-BAY': 'Baylor Bears',
  'WNCAAB-BAY': 'Baylor Bears',
  'NCAAB-BAY': 'Baylor Bears',
  'NCCABB-LEN': 'Bears',
  'NCAAB-BELL': 'Bellarmine Knights',
  'WNCAAB-BELL': 'Bellarmine Knights',
  'NCCABB-BELL': 'Bellarmine Knights',
  'NCCABB-BEL': 'Belmont Bruins',
  'NCCABB-BET': 'Bethany (KS) Bethany (KS)',
  'NCCABB-BCU': 'Bethune-cookman Wildcats',
  'NCAAF-BCU': 'Bethune-cookman Wildcats',
  'NCCABB-BING': 'Binghamton Bearcats',
  'NCCABB-BSC': 'Birmingham Southern Panthers',
  'WNCAAB-BOIS': 'Boise State Broncos',
  'NCCABB-BOIS': 'Boise State Broncos',
  'NCAAF-BOIS': 'Boise State Broncos',
  'NCAAB-BOIS': 'Boise State Broncos',
  'NHL-BOS': 'Boston Bruins',
  'NBA-BOS': 'Boston Celtics',
  'WNCAAB-BC': 'Boston College Eagles',
  'NCAAF-BC': 'Boston College Eagles',
  'NCCABB-BC': 'Boston College Eagles',
  'NCAAB-BC': 'Boston College Eagles',
  'PWHL-BOS': 'Boston Fleet',
  'MLB-BOS': 'Boston Red Sox',
  'NCCABB-BU': 'Boston University Terriers',
  'NCCABB-BGSU': 'Bowling Green Falcons',
  'NCAAF-BGSU': 'Bowling Green Falcons',
  'WNCAAB-BRAD': 'Bradley Braves',
  'NCAAB-BRAD': 'Bradley Braves',
  'NCCABB-BRAD': 'Bradley Braves',
  'NCAAF-BRST': 'Bridgewater State Bears',
  'NCCABB-CPP': 'Broncos',
  'NBA-BKN': 'Brooklyn Nets',
  'NCCABB-BRWN': 'Brown Bears',
  'WNCAAB-BRWN': 'Brown Bears',
  'NCCABB-BRY': 'Bryant Bulldogs',
  'NCCABB-BUCK': 'Bucknell Bison',
  'NCAAF-BUENA': 'Buena Vista Beavers',
  'NFL-BUF': 'Buffalo Bills',
  'NCAAF-BUFF': 'Buffalo Bulls',
  'NCAAB-BUF': 'Buffalo Bulls',
  'NCCABB-BUF': 'Buffalo Bulls',
  'NHL-BUF': 'Buffalo Sabres',
  'NCAAB-BUT': 'Butler Bulldogs',
  'NCCABB-BUT': 'Butler Bulldogs',
  'NCCABB-BYU': 'Byu Cougars',
  'NCAAF-BYU': 'Byu Cougars',
  'WNCAAB-BYU': 'Byu Cougars',
  'NCAAB-BYU': 'Byu Cougars',
  'NCCABB-CP': 'Cal Poly Mustangs',
  'NCAAB-CP': 'Cal Poly Mustangs',
  'NCAAF-CP': 'Cal Poly Mustangs',
  'WNCAAB-CP': 'Cal Poly Mustangs',
  'NCCABB-CSUB': 'Cal State Bakersfield Roadrunners',
  'NCCABB-CSUF': 'Cal State Fullerton Titans',
  'NCCABB-CSUN': 'Cal State Northridge Matadors',
  'NHL-CGY': 'Calgary Flames',
  'NCCABB-CBU': 'California Baptist Lancers',
  'WNCAAB-CAL': 'California Golden Bears',
  'NCAAF-CAL': 'California Golden Bears',
  'NCCABB-CAL': 'California Golden Bears',
  'NCAAB-CAL': 'California Golden Bears',
  'NCAAF-CAM': 'Campbell Fighting Camels',
  'NCCABB-CAM': 'Campbell Fighting Camels',
  'OLYMPICS-HOCKEY-MEN-CAN': 'Canada',
  'OLYMPICS-HOCKEY-WOMEN-CAN': 'Canada',
  'NCCABB-CAN': 'Canisius Golden Griffins',
  'NHL-CAR': 'Carolina Hurricanes',
  'NFL-CAR': 'Carolina Panthers',
  'NCAAF-CAR': 'Carroll University (WI) Pioneers',
  'NCCABB-CENT': 'Centenary Gentlemen',
  'NCCABB-CARK': 'Central Arkansas Bears',
  'NCCABB-CCSU': 'Central Connecticut Blue Devils',
  'NCCABB-CMU': 'Central Michigan Chippewas',
  'NCCABB-CAO': 'Central Missouri State Mules',
  'MLS-MTL': 'Cf Montréal',
  'NCCABB-COFC': 'Charleston Cougars',
  'NCCABB-CHSO': 'Charleston Southern Buccaneers',
  'NCCABB-CLT': 'Charlotte 49ers',
  'NCAAF-CLT': 'Charlotte 49ers',
  'MLS-CLT': 'Charlotte Fc',
  'NBA-CHA': 'Charlotte Hornets',
  'NCCABB-UTC': 'Chattanooga Mocs',
  'NFL-CHI': 'Chicago Bears',
  'NHL-CHI': 'Chicago Blackhawks',
  'NBA-CHI': 'Chicago Bulls',
  'MLB-CHC': 'Chicago Cubs',
  'MLS-CHI': 'Chicago Fire Fc',
  'WNBA-CHI': 'Chicago Sky',
  'NCCABB-CHST': 'Chicago St Cougars',
  'MLB-CHW': 'Chicago White Sox',
  'NCCABB-CIN': 'Cincinnati Bearcats',
  'NCAAB-CIN': 'Cincinnati Bearcats',
  'WNCAAB-CIN': 'Cincinnati Bearcats',
  'NCAAF-CIN': 'Cincinnati Bearcats',
  'NFL-CIN': 'Cincinnati Bengals',
  'MLB-CIN': 'Cincinnati Reds',
  'NCAAF-CLA': 'Claremont-mudd-scripps College Stags/athenas',
  'NCCABB-COP': 'Clcc Clcc',
  'NCCABB-CLEM': 'Clemson Tigers',
  'NCAAB-CLEM': 'Clemson Tigers',
  'WNCAAB-CLEM': 'Clemson Tigers',
  'NCAAF-CLEM': 'Clemson Tigers',
  'NFL-CLE': 'Cleveland Browns',
  'NBA-CLE': 'Cleveland Cavaliers',
  'MLB-CLE': 'Cleveland Guardians',
  'NCCABB-CLE': 'Cleveland State Vikings',
  'NCCABB-CCU': 'Coastal Carolina Chanticleers',
  'NCAAF-CCU': 'Coastal Carolina Chanticleers',
  'NCCABB-COE': 'Coe College Kohawks',
  'NCAAF-COLBY': 'Colby College White Mules',
  'NCCABB-COLG': 'Colgate Raiders',
  'NHL-COL': 'Colorado Avalanche',
  'NCCABB-COLO': 'Colorado Buffaloes',
  'NCAAF-COLO': 'Colorado Buffaloes',
  'WNCAAB-COLO': 'Colorado Buffaloes',
  'NCAAB-COLO': 'Colorado Buffaloes',
  'NCAAF-MESA': 'Colorado Mesa Mavericks',
  'MLS-COL': 'Colorado Rapids',
  'MLB-COL': 'Colorado Rockies',
  'NCAAB-CSU': 'Colorado State Rams',
  'NCAAF-CSU': 'Colorado State Rams',
  'NCCABB-CSU': 'Colorado State Rams',
  'WNCAAB-CSU': 'Colorado State Rams',
  'WNCAAB-COLU': 'Columbia Lions',
  'NCCABB-COLU': 'Columbia Lions',
  'NHL-CBJ': 'Columbus Blue Jackets',
  'MLS-CLB': 'Columbus Crew',
  'WNBA-CON': 'Connecticut Sun',
  'WNCAAB-COPP': 'Coppin State Eagles',
  'NCCABB-COPP': 'Coppin State Eagles',
  'NCCABB-COR': 'Cornell Big Red',
  'WNCAAB-COR': 'Cornell Big Red',
  'WNCAAB-CREI': 'Creighton Bluejays',
  'NCAAB-CREI': 'Creighton Bluejays',
  'NCCABB-CREI': 'Creighton Bluejays',
  'NCAAF-CUR': 'Curry College Colonels',
  'OLYMPICS-HOCKEY-MEN-CZE': 'Czechia',
  'OLYMPICS-HOCKEY-WOMEN-CZE': 'Czechia',
  'MLS-DC': 'D.c. United',
  'NCCABB-DBU': 'Dallas Baptist Patriots',
  'NFL-DAL': 'Dallas Cowboys',
  'NBA-DAL': 'Dallas Mavericks',
  'NHL-DAL': 'Dallas Stars',
  'WNBA-DAL': 'Dallas Wings',
  'WNCAAB-DART': 'Dartmouth Big Green',
  'NCCABB-DART': 'Dartmouth Big Green',
  'NCCABB-DAV': 'Davidson Wildcats',
  'NCAAB-DAV': 'Davidson Wildcats',
  'NCAAB-DAY': 'Dayton Flyers',
  'NCCABB-DAY': 'Dayton Flyers',
  'WNCAAB-DEL': 'Delaware Blue Hens',
  'NCAAB-DEL': 'Delaware Blue Hens',
  'NCAAF-DEL': 'Delaware Blue Hens',
  'NCCABB-DEL': 'Delaware Blue Hens',
  'NCCABB-DSU': 'Delaware State Hornets',
  'OLYMPICS-HOCKEY-MEN-DEN': 'Denmark',
  'NFL-DEN': 'Denver Broncos',
  'NBA-DEN': 'Denver Nuggets',
  'NCCABB-DEN': 'Denver Pioneers',
  'NCAAB-DEP': 'Depaul Blue Demons',
  'WNCAAB-DEP': 'Depaul Blue Demons',
  'NCCABB-DEP': 'Depauw Tigers',
  'NFL-DET': 'Detroit Lions',
  'NCCABB-DETM': 'Detroit Mercy Titans',
  'NBA-DET': 'Detroit Pistons',
  'NHL-DET': 'Detroit Red Wings',
  'MLB-DET': 'Detroit Tigers',
  'NCCABB-DRKE': 'Drake Bulldogs',
  'NCCABB-DREX': 'Drexel Dragons',
  'NCAAF-DUB': 'Dubuque Spartans',
  'WNCAAB-DUKE': 'Duke Blue Devils',
  'NCCABB-DUKE': 'Duke Blue Devils',
  'NCAAB-DUKE': 'Duke Blue Devils',
  'NCAAF-DUKE': 'Duke Blue Devils',
  'NCCABB-DUQ': 'Duquesne Dukes',
  'NCAAF-DUQ': 'Duquesne Dukes',
  'NCAAB-DUQ': 'Duquesne Dukes',
  'NCAAF-ECU': 'East Carolina Pirates',
  'NCCABB-ECU': 'East Carolina Pirates',
  'NCCABB-ETSU': 'East Tennessee State Buccaneers',
  'NCAAF-ETSU': 'East Tennessee State Buccaneers',
  'NCCABB-EIU': 'Eastern Illinois Panthers',
  'NCAAF-EIU': 'Eastern Illinois Panthers',
  'NCCABB-EKU': 'Eastern Kentucky Colonels',
  'NCAAF-EMU': 'Eastern Michigan Eagles',
  'NCCABB-EMU': 'Eastern Michigan Eagles',
  'NCCABB-EWU': 'Eastern Washington Eagles',
  'NCAAF-EWU': 'Eastern Washington Eagles',
  'NHL-EDM': 'Edmonton Oilers',
  'NCAAF-ELM': 'Elmhurst Bluejays',
  'NCCABB-ELON': 'Elon Phoenix',
  'NCCABB-EMP': 'Emporia St Hornets',
  'NCCABB-EVAN': 'Evansville Purple Aces',
  'NCCABB-FAIR': 'Fairfield Stags',
  'NCCABB-FDU': 'Fairleigh Dickinson Knights',
  'MLS-CIN': 'Fc Cincinnati',
  'MLS-DAL': 'Fc Dallas',
  'NCCABB-FLO': 'Fdtc Fdtc',
  'OLYMPICS-HOCKEY-MEN-FIN': 'Finland',
  'OLYMPICS-HOCKEY-WOMEN-FIN': 'Finland',
  'NCCABB-FRN': 'Florence Patriots',
  'WNCAAB-FAMU': 'Florida A&m Rattlers',
  'NCAAF-FAMU': 'Florida A&m Rattlers',
  'NCCABB-FAMU': 'Florida A&m Rattlers',
  'NCAAB-FAMU': 'Florida A&m Rattlers',
  'NCAAF-FAU': 'Florida Atlantic Owls',
  'NCCABB-FAU': 'Florida Atlantic Owls',
  'NCCABB-FLA': 'Florida Gators',
  'WNCAAB-FLA': 'Florida Gators',
  'NCAAF-FLA': 'Florida Gators',
  'NCAAB-FLA': 'Florida Gators',
  'NCCABB-FGCU': 'Florida Gulf Coast Eagles',
  'NCCABB-FIU': 'Florida International Panthers',
  'NHL-FLA': 'Florida Panthers',
  'NCCABB-FSC': 'Florida Southern Moccasins',
  'NCAAB-FSU': 'Florida State Seminoles',
  'WNCAAB-FSU': 'Florida State Seminoles',
  'NCCABB-FSU': 'Florida State Seminoles',
  'NCAAF-FSU': 'Florida State Seminoles',
  'NCCABB-FOR': 'Fordham Rams',
  'NCCABB-NOV': 'Fort Lauderdale Sharks',
  'OLYMPICS-HOCKEY-MEN-FRA': 'France',
  'OLYMPICS-HOCKEY-WOMEN-FRA': 'France',
  'NCCABB-FRES': 'Fresno State Bulldogs',
  'NCAAF-FRES': 'Fresno State Bulldogs',
  'NCAAF-FUR': 'Furman Paladins',
  'NCCABB-FUR': 'Furman Paladins',
  'NCCABB-GWEB': 'Gardner-webb Runnin\' Bulldogs',
  'NCCABB-GMU': 'George Mason Patriots',
  'NCAAB-GW': 'George Washington Revolutionaries',
  'NCCABB-GW': 'George Washington Revolutionaries',
  'WNCAAB-GW': 'George Washington Revolutionaries',
  'NCCABB-GTWN': 'Georgetown Hoyas',
  'WNCAAB-GTWN': 'Georgetown Hoyas',
  'NCAAB-GTWN': 'Georgetown Hoyas',
  'NCAAF-GTWN': 'Georgetown Hoyas',
  'NCCABB-UGA': 'Georgia Bulldogs',
  'NCAAF-UGA': 'Georgia Bulldogs',
  'NCAAB-UGA': 'Georgia Bulldogs',
  'WNCAAB-UGA': 'Georgia Lady Bulldogs',
  'NCAAF-GASO': 'Georgia Southern Eagles',
  'NCCABB-GASO': 'Georgia Southern Eagles',
  'NCAAF-GAST': 'Georgia State Panthers',
  'NCCABB-GAST': 'Georgia State Panthers',
  'NCAAB-GT': 'Georgia Tech Yellow Jackets',
  'WNCAAB-GT': 'Georgia Tech Yellow Jackets',
  'NCAAF-GT': 'Georgia Tech Yellow Jackets',
  'NCCABB-GT': 'Georgia Tech Yellow Jackets',
  'OLYMPICS-HOCKEY-WOMEN-GER': 'Germany',
  'OLYMPICS-HOCKEY-MEN-GER': 'Germany',
  'WNBA-GS': 'Golden State Valkyries',
  'NBA-GS': 'Golden State Warriors',
  'NCCABB-GONZ': 'Gonzaga Bulldogs',
  'NCAAB-GONZ': 'Gonzaga Bulldogs',
  'NCAAF-GRAM': 'Grambling Tigers',
  'NCCABB-GRAM': 'Grambling Tigers',
  'NCCABB-GCU': 'Grand Canyon Lopes',
  'NCAAB-GCU': 'Grand Canyon Lopes',
  'NCCABB-GRA': 'Grand View Vikings',
  'NFL-GB': 'Green Bay Packers',
  'NCCABB-GB': 'Green Bay Phoenix',
  'NCAAF-GRI': 'Grinnell Pioneers',
  'NCCABB-HAMP': 'Hampton Pirates',
  'NCCABB-HART': 'Hartford Hawks',
  'NCCABB-HARV': 'Harvard Crimson',
  'WNCAAB-HARV': 'Harvard Crimson',
  'NCCABB-HILO': 'Hawai\'i Hilo Vulcans',
  'WNCAAB-HAW': 'Hawai\'i Rainbow Wahine',
  'NCAAF-HAW': 'Hawai\'i Rainbow Warriors',
  'NCAAB-HAW': 'Hawai\'i Rainbow Warriors',
  'NCCABB-HAW': 'Hawai\'i Rainbow Warriors',
  'NCCABB-HPU': 'High Point Panthers',
  'NCCABB-HOF': 'Hofstra Pride',
  'NCCABB-HC': 'Holy Cross Crusaders',
  'MLB-HOU': 'Houston Astros',
  'NCCABB-HCU': 'Houston Christian Huskies',
  'NCAAF-HOU': 'Houston Cougars',
  'NCCABB-HOU': 'Houston Cougars',
  'NCAAB-HOU': 'Houston Cougars',
  'WNCAAB-HOU': 'Houston Cougars',
  'MLS-HOU': 'Houston Dynamo Fc',
  'NBA-HOU': 'Houston Rockets',
  'NFL-HOU': 'Houston Texans',
  'NCCABB-HOW': 'Howard Bison',
  'NCAAB-HOW': 'Howard Bison',
  'NCAAF-HOW': 'Howard Bison',
  'WNCAAB-HOW': 'Howard Bison',
  'NCCABB-IDST': 'Idaho State Bengals',
  'NCAAF-IDST': 'Idaho State Bengals',
  'WNCAAB-IDHO': 'Idaho Vandals',
  'NCAAB-IDHO': 'Idaho Vandals',
  'NCCABB-IDHO': 'Idaho Vandals',
  'NCAAF-IDHO': 'Idaho Vandals',
  'NCCABB-ILL': 'Illinois Fighting Illini',
  'WNCAAB-ILL': 'Illinois Fighting Illini',
  'NCAAF-ILL': 'Illinois Fighting Illini',
  'NCAAB-ILL': 'Illinois Fighting Illini',
  'NCCABB-ILST': 'Illinois State Redbirds',
  'NCCABB-UIW': 'Incarnate Word Cardinals',
  'WNBA-IND': 'Indiana Fever',
  'NCCABB-IU': 'Indiana Hoosiers',
  'NCAAB-IU': 'Indiana Hoosiers',
  'NCAAF-IU': 'Indiana Hoosiers',
  'WNCAAB-IU': 'Indiana Hoosiers',
  'NBA-IND': 'Indiana Pacers',
  'NCCABB-INST': 'Indiana State Sycamores',
  'NCAAF-INST': 'Indiana State Sycamores',
  'NFL-IND': 'Indianapolis Colts',
  'MLS-MIA': 'Inter Miami Cf',
  'NCCABB-IONA': 'Iona Gaels',
  'NCCABB-IOWA': 'Iowa Hawkeyes',
  'NCAAB-IOWA': 'Iowa Hawkeyes',
  'WNCAAB-IOWA': 'Iowa Hawkeyes',
  'NCAAF-IOWA': 'Iowa Hawkeyes',
  'NCAAB-ISU': 'Iowa State Cyclones',
  'NCAAF-ISU': 'Iowa State Cyclones',
  'WNCAAB-ISU': 'Iowa State Cyclones',
  'NCCABB-ISU': 'Iowa State Cyclones',
  'OLYMPICS-HOCKEY-MEN-ITA': 'Italy',
  'OLYMPICS-HOCKEY-WOMEN-ITA': 'Italy',
  'WNCAAB-IUIN': 'Iu Indianapolis Jaguars',
  'NCAAB-IUIN': 'Iu Indianapolis Jaguars',
  'NCCABB-IUIN': 'Iu Indianapolis Jaguars',
  'NCCABB-JKST': 'Jackson State Tigers',
  'NCCABB-JAX': 'Jacksonville Dolphins',
  'NFL-JAX': 'Jacksonville Jaguars',
  'NCAAB-JXST': 'Jacksonville State Gamecocks',
  'NCCABB-JVST': 'Jacksonville State Gamecocks',
  'WNCAAB-JXST': 'Jacksonville State Gamecocks',
  'NCAAF-JXST': 'Jacksonville State Gamecocks',
  'NCCABB-JOH': 'Jalc Jalc',
  'NCCABB-JMU': 'James Madison Dukes',
  'NCAAF-JMU': 'James Madison Dukes',
  'OLYMPICS-HOCKEY-WOMEN-JPN': 'Japan',
  'NFL-KC': 'Kansas City Chiefs',
  'NCCABB-KC': 'Kansas City Roos',
  'MLB-KC': 'Kansas City Royals',
  'NCCABB-KU': 'Kansas Jayhawks',
  'NCAAB-KU': 'Kansas Jayhawks',
  'WNCAAB-KU': 'Kansas Jayhawks',
  'NCAAF-KU': 'Kansas Jayhawks',
  'NCCABB-KSU': 'Kansas State Wildcats',
  'NCAAB-KSU': 'Kansas State Wildcats',
  'NCAAF-KSU': 'Kansas State Wildcats',
  'WNCAAB-KSU': 'Kansas State Wildcats',
  'NCAAF-KENN': 'Kennesaw State Owls',
  'NCCABB-KENN': 'Kennesaw State Owls',
  'NCAAB-KENT': 'Kent State Golden Flashes',
  'NCCABB-KENT': 'Kent State Golden Flashes',
  'NCAAF-KENT': 'Kent State Golden Flashes',
  'NCCABB-UK': 'Kentucky Wildcats',
  'NCAAF-UK': 'Kentucky Wildcats',
  'NCAAB-UK': 'Kentucky Wildcats',
  'WNCAAB-UK': 'Kentucky Wildcats',
  'NBA-LAC': 'La Clippers',
  'MLS-LA': 'La Galaxy',
  'NCCABB-LAS': 'La Salle Explorers',
  'NCCABB-LAF': 'Lafayette Leopards',
  'NCAAF-LAF': 'Lafayette Leopards',
  'MLS-LAFC': 'Lafc',
  'NCCABB-LAM': 'Lamar Cardinals',
  'WNBA-LV': 'Las Vegas Aces',
  'NFL-LV': 'Las Vegas Raiders',
  'OLYMPICS-HOCKEY-MEN-LAT': 'Latvia',
  'NCCABB-LEM': 'Le Moyne Dolphins',
  'NCCABB-LEH': 'Lehigh Mountain Hawks',
  'NCCABB-LIB': 'Liberty Flames',
  'NCCABB-LNC': 'Lincoln Lions',
  'NCCABB-LIN': 'Linfield Wildcats',
  'NCCABB-LIP': 'Lipscomb Bisons',
  'NCCABB-LR': 'Little Rock Trojans',
  'NCCABB-LBSU': 'Long Beach State Beach',
  'NCCABB-LIU': 'Long Island University Sharks',
  'NCAAF-LIU': 'Long Island University Sharks',
  'NCCABB-LONG': 'Longwood Lancers',
  'NCCABB-LOR': 'Loras College Duhawks',
  'MLB-LAA': 'Los Angeles Angels',
  'NFL-LAC': 'Los Angeles Chargers',
  'MLB-LAD': 'Los Angeles Dodgers',
  'NHL-LA': 'Los Angeles Kings',
  'NBA-LAL': 'Los Angeles Lakers',
  'NFL-LAR': 'Los Angeles Rams',
  'WNBA-LA': 'Los Angeles Sparks',
  'NCAAF-UL': 'Louisiana Ragin\' Cajuns',
  'NCCABB-UL': 'Louisiana Ragin\' Cajuns',
  'NCAAF-LT': 'Louisiana Tech Bulldogs',
  'NCCABB-LT': 'Louisiana Tech Bulldogs',
  'NCAAF-LOU': 'Louisville Cardinals',
  'NCCABB-LOU': 'Louisville Cardinals',
  'WNCAAB-LOU': 'Louisville Cardinals',
  'NCAAB-LOU': 'Louisville Cardinals',
  'NCCABB-LUC': 'Loyola Chicago Ramblers',
  'NCCABB-L-MD': 'Loyola Maryland Greyhounds',
  'NCCABB-LMU': 'Loyola Marymount Lions',
  'NCAAB-LMU': 'Loyola Marymount Lions',
  'WNCAAB-LSU': 'Lsu Tigers',
  'NCAAB-LSU': 'Lsu Tigers',
  'NCAAF-LSU': 'Lsu Tigers',
  'NCCABB-LSU': 'Lsu Tigers',
  'NCAAF-LUT': 'Luther Norse',
  'NCAAF-ME': 'Maine Black Bears',
  'NCCABB-ME': 'Maine Black Bears',
  'NCCABB-MAN': 'Manhattan Jaspers',
  'NCCABB-MRST': 'Marist Red Foxes',
  'NCCABB-MARQ': 'Marquette Golden Eagles',
  'NCAAB-MARQ': 'Marquette Golden Eagles',
  'NCAAF-MRSH': 'Marshall Thundering Herd',
  'NCCABB-MRSH': 'Marshall Thundering Herd',
  'NCCABB-UMES': 'Maryland Eastern Shore Hawks',
  'NCAAF-MD': 'Maryland Terrapins',
  'WNCAAB-MD': 'Maryland Terrapins',
  'NCAAB-MD': 'Maryland Terrapins',
  'NCCABB-MD': 'Maryland Terrapins',
  'NCCABB-MASS': 'Massachusetts Minutemen',
  'NCAAB-MASS': 'Massachusetts Minutemen',
  'NCAAF-MASS': 'Massachusetts Minutemen',
  'NCCABB-MCN': 'Mcneese Cowboys',
  'NBA-MEM': 'Memphis Grizzlies',
  'NCAAF-MEM': 'Memphis Tigers',
  'NCCABB-MEM': 'Memphis Tigers',
  'NCAAF-MER': 'Mercer Bears',
  'NCCABB-MER': 'Mercyhurst Lakers',
  'NCCABB-MRMK': 'Merrimack Warriors',
  'NCCABB-M-OH': 'Miami (OH) Redhawks',
  'NCAAF-M-OH': 'Miami (OH) Redhawks',
  'NCAAB-M-OH': 'Miami (OH) Redhawks',
  'NFL-MIA': 'Miami Dolphins',
  'NCCABB-STFL': 'Miami Gardens Bobcats',
  'NBA-MIA': 'Miami Heat',
  'NCAAB-MIA': 'Miami Hurricanes',
  'NCAAF-MIA': 'Miami Hurricanes',
  'NCCABB-MIA': 'Miami Hurricanes',
  'WNCAAB-MIA': 'Miami Hurricanes',
  'MLB-MIA': 'Miami Marlins',
  'NCCABB-MSU': 'Michigan State Spartans',
  'NCAAB-MSU': 'Michigan State Spartans',
  'WNCAAB-MSU': 'Michigan State Spartans',
  'NCAAF-MSU': 'Michigan State Spartans',
  'WNCAAB-MICH': 'Michigan Wolverines',
  'NCCABB-MICH': 'Michigan Wolverines',
  'NCAAB-MICH': 'Michigan Wolverines',
  'NCAAF-MICH': 'Michigan Wolverines',
  'NCCABB-MCA': 'Mid-america Christian Evangels',
  'NCCABB-MTSU': 'Middle Tennessee Blue Raiders',
  'NCAAF-MIL': 'Millikin Big Blue',
  'MLB-MIL': 'Milwaukee Brewers',
  'NBA-MIL': 'Milwaukee Bucks',
  'NCCABB-MILW': 'Milwaukee Panthers',
  'PWHL-MIN': 'Minnesota Frost',
  'NCCABB-MINN': 'Minnesota Golden Gophers',
  'NCAAF-MINN': 'Minnesota Golden Gophers',
  'NCAAB-MINN': 'Minnesota Golden Gophers',
  'WNCAAB-MINN': 'Minnesota Golden Gophers',
  'WNBA-MIN': 'Minnesota Lynx',
  'NBA-MIN': 'Minnesota Timberwolves',
  'MLB-MIN': 'Minnesota Twins',
  'MLS-MIN': 'Minnesota United Fc',
  'NFL-MIN': 'Minnesota Vikings',
  'NHL-MIN': 'Minnesota Wild',
  'WNCAAB-MSST': 'Mississippi State Bulldogs',
  'NCAAF-MSST': 'Mississippi State Bulldogs',
  'NCAAB-MSST': 'Mississippi State Bulldogs',
  'NCCABB-MSST': 'Mississippi State Bulldogs',
  'NCCABB-MVSU': 'Mississippi Valley State Delta Devils',
  'NCAAF-MOST': 'Missouri State Bears',
  'NCCABB-MOST': 'Missouri State Bears',
  'NCAAF-MIZ': 'Missouri Tigers',
  'NCAAB-MIZ': 'Missouri Tigers',
  'NCCABB-MIZ': 'Missouri Tigers',
  'WNCAAB-MIZ': 'Missouri Tigers',
  'NCCABB-MONM': 'Monmouth Hawks',
  'NCAAF-MONT': 'Montana Grizzlies',
  'NCCABB-MONT': 'Montana Grizzlies',
  'NCCABB-MTST': 'Montana State Bobcats',
  'NHL-MTL': 'Montreal Canadiens',
  'PWHL-MTL': 'Montréal Victoire',
  'NCCABB-MORE': 'Morehead State Eagles',
  'NCAAF-MOR': 'Morehouse College Maroon Tigers',
  'NCCABB-MORG': 'Morgan State Bears',
  'NCAAF-MORG': 'Morgan State Bears',
  'NCCABB-MSM': 'Mount St. Mary\'s Mountaineers',
  'NCCABB-CRIA': 'Mount Vernon Rams',
  'NCAAF-MUR': 'Murray State Racers',
  'NCCABB-MUR': 'Murray State Racers',
  'NCAAB-MUR': 'Murray State Racers',
  'WNCAAB-MUR': 'Murray State Racers',
  'NCCABB-BAC': 'Muskogee Bacone',
  'NHL-NSH': 'Nashville Predators',
  'MLS-NSH': 'Nashville Sc',
  'NCCABB-NAVY': 'Navy Midshipmen',
  'NCAAF-NAVY': 'Navy Midshipmen',
  'NCAAB-NCSU': 'Nc State Wolfpack',
  'NCCABB-NCSU': 'Nc State Wolfpack',
  'WNCAAB-NCSU': 'Nc State Wolfpack',
  'NCAAF-NCSU': 'Nc State Wolfpack',
  'WNCAAB-NEB': 'Nebraska Cornhuskers',
  'NCAAF-NEB': 'Nebraska Cornhuskers',
  'NCCABB-NEB': 'Nebraska Cornhuskers',
  'NCAAB-NEB': 'Nebraska Cornhuskers',
  'NCCABB-NK': 'Nebraska-kearney Lopers',
  'NCCABB-NEV': 'Nevada Wolf Pack',
  'NCAAB-NEV': 'Nevada Wolf Pack',
  'NFL-NE': 'New England Patriots',
  'MLS-NE': 'New England Revolution',
  'NCCABB-UNH': 'New Hampshire Wildcats',
  'NCAAF-UNH': 'New Hampshire Wildcats',
  'NCCABB-NHVN': 'New Haven Chargers',
  'NHL-NJ': 'New Jersey Devils',
  'NCAAF-UNM': 'New Mexico Lobos',
  'NCCABB-UNM': 'New Mexico Lobos',
  'NCCABB-NMSU': 'New Mexico State Aggies',
  'NCAAF-NMSU': 'New Mexico State Aggies',
  'NBA-NO': 'New Orleans Pelicans',
  'NCCABB-UNO': 'New Orleans Privateers',
  'NFL-NO': 'New Orleans Saints',
  'MLS-NYC': 'New York City Fc',
  'NFL-NYG': 'New York Giants',
  'NHL-NYI': 'New York Islanders',
  'NFL-NYJ': 'New York Jets',
  'NBA-NY': 'New York Knicks',
  'WNBA-NY': 'New York Liberty',
  'MLB-NYM': 'New York Mets',
  'NHL-NYR': 'New York Rangers',
  'MLS-NY': 'New York Red Bulls',
  'PWHL-NY': 'New York Sirens',
  'MLB-NYY': 'New York Yankees',
  'NCCABB-NIA': 'Niagara Purple Eagles',
  'NCCABB-NICH': 'Nicholls Colonels',
  'NCAAF-NICH': 'Nicholls Colonels',
  'NCCABB-NJIT': 'Njit Highlanders',
  'NCCABB-NORF': 'Norfolk State Spartans',
  'NCAAF-NORF': 'Norfolk State Spartans',
  'NCCABB-UNA': 'North Alabama Lions',
  'NCAAF-UNA': 'North Alabama Lions',
  'NCCABB-NCAT': 'North Carolina A&t Aggies',
  'NCCABB-NCCU': 'North Carolina Central Eagles',
  'NCAAB-UNC': 'North Carolina Tar Heels',
  'NCCABB-UNC': 'North Carolina Tar Heels',
  'NCAAF-UNC': 'North Carolina Tar Heels',
  'WNCAAB-UNC': 'North Carolina Tar Heels',
  'NCAAF-UND': 'North Dakota Fighting Hawks',
  'NCCABB-UND': 'North Dakota Fighting Hawks',
  'NCCABB-NDSU': 'North Dakota State Bison',
  'NCCABB-UNF': 'North Florida Ospreys',
  'NCCABB-NGA': 'North Georgia Saints',
  'NCAAF-NOR': 'North Park Vikings',
  'NCCABB-UNT': 'North Texas Mean Green',
  'NCAAF-UNT': 'North Texas Mean Green',
  'NCCABB-NE': 'Northeastern Huskies',
  'NCAAF-NAU': 'Northern Arizona Lumberjacks',
  'NCCABB-NAU': 'Northern Arizona Lumberjacks',
  'NCCABB-UNCO': 'Northern Colorado Bears',
  'NCAAF-NIU': 'Northern Illinois Huskies',
  'NCCABB-NIU': 'Northern Illinois Huskies',
  'NCAAB-NIU': 'Northern Illinois Huskies',
  'NCAAF-UNI': 'Northern Iowa Panthers',
  'NCCABB-UNI': 'Northern Iowa Panthers',
  'NCCABB-NKU': 'Northern Kentucky Norse',
  'NCAAB-NKU': 'Northern Kentucky Norse',
  'WNCAAB-NKU': 'Northern Kentucky Norse',
  'NCCABB-NOR': 'Northwestern College (IA) Northwestern College (Ia)',
  'NCCABB-NWST': 'Northwestern State Demons',
  'WNCAAB-NU': 'Northwestern Wildcats',
  'NCAAF-NU': 'Northwestern Wildcats',
  'NCAAB-NU': 'Northwestern Wildcats',
  'NCCABB-NU': 'Northwestern Wildcats',
  'WNCAAB-ND': 'Notre Dame Fighting Irish',
  'NCAAF-ND': 'Notre Dame Fighting Irish',
  'NCAAB-ND': 'Notre Dame Fighting Irish',
  'NCCABB-ND': 'Notre Dame Fighting Irish',
  'NCCABB-NYIT': 'Ny Institute Of Technology Yellow Jackets',
  'NCCABB-OAK': 'Oakland Golden Grizzlies',
  'NCAAF-OHIO': 'Ohio Bobcats',
  'NCCABB-OHIO': 'Ohio Bobcats',
  'NCAAF-OSU': 'Ohio State Buckeyes',
  'NCAAB-OSU': 'Ohio State Buckeyes',
  'NCCABB-OSU': 'Ohio State Buckeyes',
  'WNCAAB-OSU': 'Ohio State Buckeyes',
  'NBA-OKC': 'Oklahoma City Thunder',
  'NCAAF-OU': 'Oklahoma Sooners',
  'NCCABB-OU': 'Oklahoma Sooners',
  'WNCAAB-OU': 'Oklahoma Sooners',
  'NCAAB-OU': 'Oklahoma Sooners',
  'NCAAF-OKST': 'Oklahoma State Cowboys',
  'NCCABB-OKST': 'Oklahoma State Cowboys',
  'NCAAB-OKST': 'Oklahoma State Cowboys',
  'WNCAAB-OKST': 'Oklahoma State Cowgirls',
  'NCAAF-ODU': 'Old Dominion Monarchs',
  'NCCABB-ODU': 'Old Dominion Monarchs',
  'NCAAB-MISS': 'Ole Miss Rebels',
  'NCCABB-MISS': 'Ole Miss Rebels',
  'WNCAAB-MISS': 'Ole Miss Rebels',
  'NCAAF-MISS': 'Ole Miss Rebels',
  'NCCABB-OMA': 'Omaha Mavericks',
  'NCCABB-ORU': 'Oral Roberts Golden Eagles',
  'NCAAB-ORE': 'Oregon Ducks',
  'WNCAAB-ORE': 'Oregon Ducks',
  'NCAAF-ORE': 'Oregon Ducks',
  'NCCABB-ORE': 'Oregon Ducks',
  'NCAAF-ORST': 'Oregon State Beavers',
  'NCCABB-ORST': 'Oregon State Beavers',
  'MLS-ORL': 'Orlando City Sc',
  'NBA-ORL': 'Orlando Magic',
  'PWHL-OTT': 'Ottawa Charge',
  'NHL-OTT': 'Ottawa Senators',
  'NCCABB-PAC': 'Pacific Tigers',
  'NCCABB-PEA': 'Pearl Pearl',
  'WNCAAB-PSU': 'Penn State Lady Lions',
  'NCCABB-PSU': 'Penn State Nittany Lions',
  'NCAAF-PSU': 'Penn State Nittany Lions',
  'NCAAB-PSU': 'Penn State Nittany Lions',
  'WNCAAB-PENN': 'Pennsylvania Quakers',
  'NCCABB-PENN': 'Pennsylvania Quakers',
  'NCAAB-PEPP': 'Pepperdine Waves',
  'NCCABB-PEPP': 'Pepperdine Waves',
  'NBA-PHI': 'Philadelphia 76ers',
  'NFL-PHI': 'Philadelphia Eagles',
  'NHL-PHI': 'Philadelphia Flyers',
  'MLB-PHI': 'Philadelphia Phillies',
  'MLS-PHI': 'Philadelphia Union',
  'WNBA-PHX': 'Phoenix Mercury',
  'NBA-PHX': 'Phoenix Suns',
  'NCCABB-LCO': 'Pineville Wildcats',
  'NCCABB-PITT': 'Pittsburgh Panthers',
  'NCAAB-PITT': 'Pittsburgh Panthers',
  'NCAAF-PITT': 'Pittsburgh Panthers',
  'WNCAAB-PITT': 'Pittsburgh Panthers',
  'NHL-PIT': 'Pittsburgh Penguins',
  'MLB-PIT': 'Pittsburgh Pirates',
  'NFL-PIT': 'Pittsburgh Steelers',
  'WNBA-POR': 'Portland Fire',
  'NCAAB-PORT': 'Portland Pilots',
  'NCCABB-PORT': 'Portland Pilots',
  'NCAAF-PRST': 'Portland State Vikings',
  'NCCABB-PRST': 'Portland State Vikings',
  'MLS-POR': 'Portland Timbers',
  'NBA-POR': 'Portland Trail Blazers',
  'NCCABB-PV': 'Prairie View A&m Panthers',
  'NCAAF-PV': 'Prairie View A&m Panthers',
  'NCCABB-PRES': 'Presbyterian Blue Hose',
  'NCCABB-PRIN': 'Princeton Tigers',
  'WNCAAB-PRIN': 'Princeton Tigers',
  'NCCABB-PROV': 'Providence Friars',
  'NCAAB-PROV': 'Providence Friars',
  'WNCAAB-PROV': 'Providence Friars',
  'WNCAAB-PUR': 'Purdue Boilermakers',
  'NCAAF-PUR': 'Purdue Boilermakers',
  'NCAAB-PUR': 'Purdue Boilermakers',
  'NCCABB-PUR': 'Purdue Boilermakers',
  'NCCABB-PFW': 'Purdue Fort Wayne Mastodons',
  'NCCABB-QUOC': 'Queens University Royals',
  'NCCABB-QUIN': 'Quinnipiac Bobcats',
  'NCCABB-RAD': 'Radford Highlanders',
  'MLS-RSL': 'Real Salt Lake',
  'NCAAF-RED': 'Redlands Bulldogs',
  'NCCABB-URI': 'Rhode Island Rams',
  'NCCABB-RICE': 'Rice Owls',
  'NCAAF-RICE': 'Rice Owls',
  'NCCABB-RICH': 'Richmond Spiders',
  'NCAAF-RICH': 'Richmond Spiders',
  'NCCABB-RID': 'Rider Broncs',
  'NCCABB-RMU': 'Robert Morris Colonials',
  'NCCABB-ROO': 'Roosevelt Lakers',
  'WNCAAB-RUTG': 'Rutgers Scarlet Knights',
  'NCAAF-RUTG': 'Rutgers Scarlet Knights',
  'NCAAB-RUTG': 'Rutgers Scarlet Knights',
  'NCCABB-RUTG': 'Rutgers Scarlet Knights',
  'NBA-SAC': 'Sacramento Kings',
  'NCAAF-SAC': 'Sacramento State Hornets',
  'WNCAAB-SAC': 'Sacramento State Hornets',
  'NCAAB-SAC': 'Sacramento State Hornets',
  'NCCABB-SAC': 'Sacramento State Hornets',
  'NCCABB-SHU': 'Sacred Heart Pioneers',
  'NCCABB-SFPA': 'Saint Francis Red Flash',
  'NCCABB-JOES': 'Saint Joseph\'s Hawks',
  'NCCABB-SLU': 'Saint Louis Billikens',
  'NCAAB-SLU': 'Saint Louis Billikens',
  'NCAAB-SMC': 'Saint Mary\'s Gaels',
  'NCCABB-SMC': 'Saint Mary\'s Gaels',
  'NCCABB-CON': 'Saint Paul Golden Bears',
  'NCCABB-SPU': 'Saint Peter\'s Peacocks',
  'NCCABB-SSU': 'Salisbury Sea Gulls',
  'NCAAF-SHSU': 'Sam Houston Bearkats',
  'NCCABB-SHSU': 'Sam Houston Bearkats',
  'NCCABB-SAM': 'Samford Bulldogs',
  'NBA-SA': 'San Antonio Spurs',
  'MLS-SD': 'San Diego Fc',
  'MLB-SD': 'San Diego Padres',
  'NCAAF-SDSU': 'San Diego State Aztecs',
  'WNCAAB-SDSU': 'San Diego State Aztecs',
  'NCCABB-SDSU': 'San Diego State Aztecs',
  'NCAAB-SDSU': 'San Diego State Aztecs',
  'NCCABB-USD': 'San Diego Toreros',
  'NFL-SF': 'San Francisco 49ers',
  'NCAAB-SF': 'San Francisco Dons',
  'NCCABB-SF': 'San Francisco Dons',
  'MLB-SF': 'San Francisco Giants',
  'MLS-SJ': 'San Jose Earthquakes',
  'NHL-SJ': 'San Jose Sharks',
  'WNCAAB-SJSU': 'San José State Spartans',
  'NCCABB-SJSU': 'San José State Spartans',
  'NCAAB-SJSU': 'San José State Spartans',
  'NCAAF-SJSU': 'San José State Spartans',
  'NCCABB-SAN': 'Sanjacjc Sanjacjc',
  'NCCABB-SCU': 'Santa Clara Broncos',
  'NCAAB-SCU': 'Santa Clara Broncos',
  'NCCABB-SAV': 'Savannah State Tigers',
  'NCCABB-STA': 'Scof Scof',
  'NCCABB-SELA': 'Se Louisiana Lions',
  'NHL-SEA': 'Seattle Kraken',
  'MLB-SEA': 'Seattle Mariners',
  'NFL-SEA': 'Seattle Seahawks',
  'MLS-SEA': 'Seattle Sounders Fc',
  'WNBA-SEA': 'Seattle Storm',
  'PWHL-SEA': 'Seattle Torrent',
  'NCCABB-SEA': 'Seattle U Redhawks',
  'NCAAB-SEA': 'Seattle U Redhawks',
  'WNCAAB-HALL': 'Seton Hall Pirates',
  'NCCABB-HALL': 'Seton Hall Pirates',
  'NCAAB-HALL': 'Seton Hall Pirates',
  'NCCABB-SIE': 'Siena Saints',
  'NCCABB-SIUE': 'Siu Edwardsville Cougars',
  'OLYMPICS-HOCKEY-MEN-SVK': 'Slovakia',
  'NCAAF-SMU': 'Smu Mustangs',
  'WNCAAB-SMU': 'Smu Mustangs',
  'NCCABB-SMU': 'Smu Mustangs',
  'NCAAB-SMU': 'Smu Mustangs',
  'WNCAAB-USA': 'South Alabama Jaguars',
  'NCAAF-USA': 'South Alabama Jaguars',
  'NCCABB-USA': 'South Alabama Jaguars',
  'NCAAB-USA': 'South Alabama Jaguars',
  'NCCABB-SC': 'South Carolina Gamecocks',
  'NCAAB-SC': 'South Carolina Gamecocks',
  'NCAAF-SC': 'South Carolina Gamecocks',
  'WNCAAB-SC': 'South Carolina Gamecocks',
  'NCCABB-SCST': 'South Carolina State Bulldogs',
  'NCCABB-UPST': 'South Carolina Upstate Spartans',
  'NCAAF-SDAK': 'South Dakota Coyotes',
  'NCCABB-SDAK': 'South Dakota Coyotes',
  'NCAAF-SDST': 'South Dakota State Jackrabbits',
  'NCCABB-SDST': 'South Dakota State Jackrabbits',
  'NCAAB-USF': 'South Florida Bulls',
  'NCAAF-USF': 'South Florida Bulls',
  'WNCAAB-USF': 'South Florida Bulls',
  'NCCABB-USF': 'South Florida Bulls',
  'NCAAF-SEMO': 'Southeast Missouri State Redhawks',
  'NCCABB-SEMO': 'Southeast Missouri State Redhawks',
  'NCAAB-SIU': 'Southern Illinois Salukis',
  'WNCAAB-SIU': 'Southern Illinois Salukis',
  'NCCABB-SIU': 'Southern Illinois Salukis',
  'NCAAF-SIU': 'Southern Illinois Salukis',
  'NCCABB-USI': 'Southern Indiana Screaming Eagles',
  'WNCAAB-USI': 'Southern Indiana Screaming Eagles',
  'NCAAF-SOU': 'Southern Jaguars',
  'NCCABB-USM': 'Southern Miss Golden Eagles',
  'NCAAF-USM': 'Southern Miss Golden Eagles',
  'NCCABB-SUU': 'Southern Utah Thunderbirds',
  'NCAAF-SUU': 'Southern Utah Thunderbirds',
  'NCCABB-SOU': 'Southwest Mustangs',
  'NCCABB-TAM': 'Spartans',
  'MLS-SKC': 'Sporting Kansas City',
  'NCCABB-SBU': 'St. Bonaventure Bonnies',
  'NCAAB-SBU': 'St. Bonaventure Bonnies',
  'NCCABB-SFBK': 'St. Francis (BKN) Terriers',
  'NCCABB-STGR': 'St. Gregory Cavaliers',
  'NCCABB-SJU': 'St. John\'s Red Storm',
  'NCAAB-SJU': 'St. John\'s Red Storm',
  'WNCAAB-SJU': 'St. John\'s Red Storm',
  'NHL-STL': 'St. Louis Blues',
  'MLB-STL': 'St. Louis Cardinals',
  'MLS-STL': 'St. Louis City Sc',
  'NCCABB-SM': 'St. Martins Saints',
  'NCCABB-ST.': 'St. Olaf Oles',
  'NCCABB-STMN': 'St. Thomas-minnesota Tommies',
  'NCAAF-STAN': 'Stanford Cardinal',
  'NCCABB-STAN': 'Stanford Cardinal',
  'NCAAB-STAN': 'Stanford Cardinal',
  'WNCAAB-STAN': 'Stanford Cardinal',
  'NCCABB-SFA': 'Stephen F. Austin Lumberjacks',
  'NCAAB-STET': 'Stetson Hatters',
  'WNCAAB-STET': 'Stetson Hatters',
  'NCCABB-STET': 'Stetson Hatters',
  'NCAAF-STET': 'Stetson Hatters',
  'NCCABB-STO': 'Stonehill Skyhawks',
  'NCCABB-STBK': 'Stony Brook Seawolves',
  'NCCABB-SWOS': 'Sw Oklahoma State Bulldogs',
  'OLYMPICS-HOCKEY-MEN-SWE': 'Sweden',
  'OLYMPICS-HOCKEY-WOMEN-SWE': 'Sweden',
  'OLYMPICS-HOCKEY-WOMEN-SUI': 'Switzerland',
  'OLYMPICS-HOCKEY-MEN-SUI': 'Switzerland',
  'NCAAF-SYR': 'Syracuse Orange',
  'NCCABB-SYR': 'Syracuse Orange',
  'NCAAB-SYR': 'Syracuse Orange',
  'NCCABB-TAB': 'Tabor',
  'NFL-TB': 'Tampa Bay Buccaneers',
  'NHL-TB': 'Tampa Bay Lightning',
  'MLB-TB': 'Tampa Bay Rays',
  'NCCABB-TAR': 'Tarleton State Texans',
  'NCCABB-TBD': 'Tbd',
  'NCAAB-TCU': 'Tcu Horned Frogs',
  'NCCABB-TCU': 'Tcu Horned Frogs',
  'WNCAAB-TCU': 'Tcu Horned Frogs',
  'NCAAF-TCU': 'Tcu Horned Frogs',
  'NCCABB-TEM': 'Temple Owls',
  'NCAAF-TEM': 'Temple Owls',
  'WNCAAB-TENN': 'Tennessee Lady Volunteers',
  'NCAAF-TNST': 'Tennessee State Tigers',
  'NCCABB-TNST': 'Tennessee State Tigers',
  'NCCABB-TNTC': 'Tennessee Tech Golden Eagles',
  'NFL-TEN': 'Tennessee Titans',
  'NCAAF-TENN': 'Tennessee Volunteers',
  'NCCABB-TENN': 'Tennessee Volunteers',
  'NCAAB-TENN': 'Tennessee Volunteers',
  'WNCAAB-TA&M': 'Texas A&m Aggies',
  'NCAAF-TA&M': 'Texas A&m Aggies',
  'NCAAB-TA&M': 'Texas A&m Aggies',
  'NCCABB-TA&M': 'Texas A&m Aggies',
  'NCCABB-AMCC': 'Texas A&m-corpus Christi Islanders',
  'WNCAAB-TEX': 'Texas Longhorns',
  'NCCABB-TEX': 'Texas Longhorns',
  'NCAAB-TEX': 'Texas Longhorns',
  'NCAAF-TEX': 'Texas Longhorns',
  'NCCABB-TL': 'Texas Lutheran Bulldogs',
  'MLB-TEX': 'Texas Rangers',
  'NCCABB-TXSO': 'Texas Southern Tigers',
  'NCCABB-TXST': 'Texas State Bobcats',
  'NCAAF-TXST': 'Texas State Bobcats',
  'WNCAAB-TTU': 'Texas Tech Lady Raiders',
  'NCCABB-TTU': 'Texas Tech Red Raiders',
  'NCAAF-TTU': 'Texas Tech Red Raiders',
  'NCAAB-TTU': 'Texas Tech Red Raiders',
  'NCCABB-UTPA': 'Texas-pan American Broncs',
  'NCCABB-CIT': 'The Citadel Bulldogs',
  'NCCABB-TOL': 'Toledo Rockets',
  'NCAAF-TOL': 'Toledo Rockets',
  'MLB-TOR': 'Toronto Blue Jays',
  'MLS-TOR': 'Toronto Fc',
  'NHL-TOR': 'Toronto Maple Leafs',
  'NBA-TOR': 'Toronto Raptors',
  'PWHL-TOR': 'Toronto Sceptres',
  'WNBA-TOR': 'Toronto Tempo',
  'NCAAF-TOW': 'Towson Tigers',
  'NCCABB-TOW': 'Towson Tigers',
  'NCAAF-TROY': 'Troy Trojans',
  'NCCABB-TROY': 'Troy Trojans',
  'NCCABB-TRST': 'Truman State Bulldogs',
  'NCAAF-TULN': 'Tulane Green Wave',
  'NCCABB-TULN': 'Tulane Green Wave',
  'NCCABB-TLSA': 'Tulsa Golden Hurricane',
  'NCAAF-TLSA': 'Tulsa Golden Hurricane',
  'NCAAB-UAB': 'Uab Blazers',
  'NCCABB-UAB': 'Uab Blazers',
  'WNCAAB-UAB': 'Uab Blazers',
  'NCAAF-UAB': 'Uab Blazers',
  'NCCABB-ALB': 'Ualbany Great Danes',
  'NCAAF-UCD': 'Uc Davis Aggies',
  'NCCABB-UCD': 'Uc Davis Aggies',
  'NCCABB-UCI': 'Uc Irvine Anteaters',
  'NCAAB-UCR': 'Uc Riverside Highlanders',
  'NCCABB-UCR': 'Uc Riverside Highlanders',
  'WNCAAB-UCR': 'Uc Riverside Highlanders',
  'NCAAB-UCSD': 'Uc San Diego Tritons',
  'NCCABB-UCSD': 'Uc San Diego Tritons',
  'WNCAAB-UCSD': 'Uc San Diego Tritons',
  'NCCABB-UCSB': 'Uc Santa Barbara Gauchos',
  'NCAAF-UCF': 'Ucf Knights',
  'WNCAAB-UCF': 'Ucf Knights',
  'NCAAB-UCF': 'Ucf Knights',
  'NCCABB-UCF': 'Ucf Knights',
  'NCAAF-UCLA': 'Ucla Bruins',
  'WNCAAB-UCLA': 'Ucla Bruins',
  'NCAAB-UCLA': 'Ucla Bruins',
  'NCCABB-UCLA': 'Ucla Bruins',
  'NCAAB-CONN': 'Uconn Huskies',
  'NCAAF-CONN': 'Uconn Huskies',
  'WNCAAB-CONN': 'Uconn Huskies',
  'NCCABB-CONN': 'Uconn Huskies',
  'WNCAAB-UIC': 'Uic Flames',
  'NCAAB-UIC': 'Uic Flames',
  'NCCABB-UIC': 'Uic Flames',
  'NCAAF-ULM': 'Ul Monroe Warhawks',
  'NCCABB-ULM': 'Ul Monroe Warhawks',
  'NCCABB-UML': 'Umass Lowell River Hawks',
  'NCCABB-UMBC': 'Umbc Retrievers',
  'NCCABB-UNCA': 'Unc Asheville Bulldogs',
  'NCCABB-UNCG': 'Unc Greensboro Spartans',
  'NCCABB-UNCW': 'Unc Wilmington Seahawks',
  'OLYMPICS-HOCKEY-WOMEN-USA': 'United States',
  'OLYMPICS-HOCKEY-MEN-USA': 'United States',
  'NCCABB-UNLV': 'Unlv Rebels',
  'NCCABB-UPP': 'Upper Iowa Peacocks',
  'NCAAF-USC': 'Usc Trojans',
  'WNCAAB-USC': 'Usc Trojans',
  'NCAAB-USC': 'Usc Trojans',
  'NCCABB-USC': 'Usc Trojans',
  'NCCABB-UTA': 'Ut Arlington Mavericks',
  'NCCABB-UTM': 'Ut Martin Skyhawks',
  'NCAAF-UTM': 'Ut Martin Skyhawks',
  'NCCABB-RGV': 'Ut Rio Grande Valley Vaqueros',
  'NBA-UTAH': 'Utah Jazz',
  'NHL-UTA': 'Utah Mammoth',
  'NCAAB-USU': 'Utah State Aggies',
  'NCAAF-USU': 'Utah State Aggies',
  'NCCABB-USU': 'Utah State Aggies',
  'NCAAF-UTU': 'Utah Tech Trailblazers',
  'NCCABB-UTU': 'Utah Tech Trailblazers',
  'NCCABB-UTAH': 'Utah Utes',
  'WNCAAB-UTAH': 'Utah Utes',
  'NCAAB-UTAH': 'Utah Utes',
  'NCAAF-UTAH': 'Utah Utes',
  'NCCABB-UVU': 'Utah Valley Wolverines',
  'NCCABB-UTEP': 'Utep Miners',
  'NCAAF-UTEP': 'Utep Miners',
  'NCCABB-UTSA': 'Utsa Roadrunners',
  'NCAAF-UTSA': 'Utsa Roadrunners',
  'NCCABB-VAL': 'Valparaiso Beacons',
  'NHL-VAN': 'Vancouver Canucks',
  'PWHL-VAN': 'Vancouver Goldeneyes',
  'MLS-VAN': 'Vancouver Whitecaps',
  'NCAAB-VAN': 'Vanderbilt Commodores',
  'NCAAF-VAN': 'Vanderbilt Commodores',
  'WNCAAB-VAN': 'Vanderbilt Commodores',
  'NCCABB-VAN': 'Vanderbilt Commodores',
  'NCCABB-VCU': 'Vcu Rams',
  'NHL-VGK': 'Vegas Golden Knights',
  'NCCABB-UVM': 'Vermont Catamounts',
  'NCCABB-VILL': 'Villanova Wildcats',
  'NCAAF-VILL': 'Villanova Wildcats',
  'WNCAAB-VILL': 'Villanova Wildcats',
  'NCAAB-VILL': 'Villanova Wildcats',
  'NCCABB-UVA': 'Virginia Cavaliers',
  'WNCAAB-UVA': 'Virginia Cavaliers',
  'NCAAF-UVA': 'Virginia Cavaliers',
  'NCAAB-UVA': 'Virginia Cavaliers',
  'NCAAF-VT': 'Virginia Tech Hokies',
  'NCAAB-VT': 'Virginia Tech Hokies',
  'NCCABB-VT': 'Virginia Tech Hokies',
  'WNCAAB-VT': 'Virginia Tech Hokies',
  'NCCABB-VMI': 'Vmi Keydets',
  'NCAAF-VMI': 'Vmi Keydets',
  'NCCABB-WAG': 'Wagner Seahawks',
  'NCAAF-WAG': 'Wagner Seahawks',
  'NCAAF-WAKE': 'Wake Forest Demon Deacons',
  'NCAAB-WAKE': 'Wake Forest Demon Deacons',
  'NCCABB-WAKE': 'Wake Forest Demon Deacons',
  'WNCAAB-WAKE': 'Wake Forest Demon Deacons',
  'NCCABB-WAR': 'Wartburg Knights',
  'NCCABB-129755': 'Waseda University Waseda Uni',
  'NHL-WSH': 'Washington Capitals',
  'NFL-WSH': 'Washington Commanders',
  'NCAAB-WASH': 'Washington Huskies',
  'NCCABB-WASH': 'Washington Huskies',
  'WNCAAB-WASH': 'Washington Huskies',
  'NCAAF-WASH': 'Washington Huskies',
  'WNBA-WSH': 'Washington Mystics',
  'MLB-WSH': 'Washington Nationals',
  'NCAAF-WSU': 'Washington State Cougars',
  'NCCABB-WSU': 'Washington State Cougars',
  'NCAAB-WSU': 'Washington State Cougars',
  'NBA-WSH': 'Washington Wizards',
  'NCCABB-WAY': 'Wayne State (NE) Wildcats',
  'NCCABB-WEB': 'Weber State Wildcats',
  'NCAAF-WEB': 'Weber State Wildcats',
  'NCCABB-WES': 'West Georgia Wolves',
  'NCAAF-WVU': 'West Virginia Mountaineers',
  'NCAAB-WVU': 'West Virginia Mountaineers',
  'WNCAAB-WVU': 'West Virginia Mountaineers',
  'NCCABB-WVU': 'West Virginia Mountaineers',
  'NCAAF-WCU': 'Western Carolina Catamounts',
  'NCCABB-WCU': 'Western Carolina Catamounts',
  'NCCABB-WIU': 'Western Illinois Leathernecks',
  'NCAAF-WIU': 'Western Illinois Leathernecks',
  'NCAAB-WKU': 'Western Kentucky Hilltoppers',
  'NCAAF-WKU': 'Western Kentucky Hilltoppers',
  'NCCABB-WKU': 'Western Kentucky Hilltoppers',
  'NCCABB-WMU': 'Western Michigan Broncos',
  'NCAAF-WMU': 'Western Michigan Broncos',
  'NCCABB-WICH': 'Wichita State Shockers',
  'NCCABB-W&M': 'William & Mary Tribe',
  'NCCABB-WIL': 'William Woods',
  'NHL-WPG': 'Winnipeg Jets',
  'NCCABB-WIN': 'Winthrop Eagles',
  'NCAAB-WIS': 'Wisconsin Badgers',
  'NCAAF-WIS': 'Wisconsin Badgers',
  'NCCABB-WIS': 'Wisconsin Badgers',
  'WNCAAB-WIS': 'Wisconsin Badgers',
  'NCCABB-UWP': 'Wisconsin-platteville Pioneers',
  'NCCABB-WOF': 'Wofford Terriers',
  'NCCABB-WRST': 'Wright State Raiders',
  'NCAAF-WYO': 'Wyoming Cowboys',
  'NCCABB-WYO': 'Wyoming Cowboys',
  'NCAAB-XAV': 'Xavier Musketeers',
  'WNCAAB-XAV': 'Xavier Musketeers',
  'NCCABB-XAV': 'Xavier Musketeers',
  'NCCABB-YALE': 'Yale Bulldogs',
  'WNCAAB-YALE': 'Yale Bulldogs',
  'NCAAB-YALE': 'Yale Bulldogs',
  'NCAAF-YALE': 'Yale Bulldogs',
  'NCAAF-YSU': 'Youngstown State Penguins',
  'NCCABB-YSU': 'Youngstown State Penguins',
};
